### ISSUE TITLE
Preamble stuff

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#104]
Currently our preamble includes the sentence:

> Users of CellML models should read the informative version of the CellML Specification which is available here: https://doi.org/science/1.1.1.10.

... where that address doesn't exist ... should it point from the PDF to the online site which contains the informative stuff too?

**Comment by agarny** [comment]
Whatever the URL is / will be, I would make it point to the URL that we are going to use in libCellML for the `Issue::url()` method.

**Comment by kerimoyle** [comment]
So it's not a publishing thing then, just a convenience thing?  I wondered about the DOI address?

**Comment by agarny** [comment]
I would say that it is/was a convenience thing, but who knows...? @nickerso?

**Comment by nickerso** [comment]
The DOI was an indication that we intend to publish the informative spec as a journal article at some point. We will finalise some of these URLs on the call tomorrow.

**Comment by kerimoyle** [comment]
Closed by #114
