### ISSUE TITLE
Format headings with monospace font in section 3?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#105]
Currently we mix monospace font and normal throughout the headings:
![image](https://user-images.githubusercontent.com/46887220/77859234-a5ab8980-7264-11ea-8756-06d350e13674.png)
Should the headings in Chapter 3 be adjusted to match the others, and perhaps changed to avoid plurals of monospace ... eg: 
- Interpretation of `import` elements
- `units` references
etc ... ?

**Comment by agarny** [comment]
Yes, I would do that.

**Comment by kerimoyle** [comment]
Closed by #108
