### ISSUE TITLE
Equation in section 3 should not be an image?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#106]
The equation in section 3 is currently an image.  Perhaps, for ease of editing/tracking/etc, it should be a `math` block instead?

**Comment by agarny** [comment]
Definitely!

**Comment by kerimoyle** [comment]
@agarny do you happen to have the file you generated the new equation from still?  If not I'll write it out.

**Comment by agarny** [comment]
Sorry, I don't, not to mention that I might have used Word for that anyway (much faster for a one-off).

**Comment by kerimoyle** [comment]
Closed by #109
