### ISSUE TITLE
Should the PDF of the normative spec have pagebreaks between Interpretation sections?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#107]
We currently have new pages between each of the Chapter 2: Element information items sections, but not in the Chapter 3: Interpretation sections.  They both range in length ... not sure which is better? Page breaks everywhere? nowhere? one chapter or another? 
![image](https://user-images.githubusercontent.com/46887220/77862473-0b554100-7278-11ea-9aac-24ad222698db.png)

**Comment by agarny** [comment]
I would only have pagebreaks between chapters. KISS. :)

**Comment by kerimoyle** [comment]
I'm all in favour of KISSing, except when it looks ugly ;). I suspect some of this will depend on the answer to #110 ...?

**Comment by agarny** [comment]
Sure, there will/might be cases where a pagebreak may be required. It's just that, as a general rule, I would only have pagebreaks between chapters.

**Comment by nickerso** [comment]
I'd like to keep the page breaks, each element generally fits on a single page and it keeps it clean to have them each on their own page. The interpretation is more about how things fit together so its not so necessary to keep each section separate.

**Comment by kerimoyle** [comment]
Without page breaks between sections:
https://cellml-specification-dev.readthedocs.io/_/downloads/en/testing_no_pagebreaks/pdf/

With page breaks in Chapters 1 and 2: 
https://cellml-specification-dev.readthedocs.io/_/downloads/en/update_to_cellml2/pdf/

**Comment by agarny** [comment]
Do we really want/need those blank pages? I would remove them. I mean, the only reason for having them for me would be for printing purposes, but who is going to print this PDF?...

Otherwise, I must confess that, on seeing the end result, I quite like with pagebreaks between sections in a chapter. I think it works nicely for this particular document.

**Comment by kerimoyle** [comment]
> Do we really want/need those blank pages? I would remove them. I mean, the only reason for having them for me would be for printing purposes, but who is going to print this PDF?...

I would have thought the only reason for supplying a PDF would be for printing?  I think they're coming from something in the template which says that a chapter must start on an odd-numbered page or something.  I'll have a look ... 

> Otherwise, I must confess that, on seeing the end result, I quite like with page breaks between sections in a chapter. I think it works nicely for this particular document.

Well, that was easy :)

**Comment by nickerso** [comment]
> I would have thought the only reason for supplying a PDF would be for printing? 

Its more for a permanent digital artifact that can be archived, shared, etc.

And yes, I'd expect the extra blank pages are coming from having chapters start on a "facing" page.

**Comment by kerimoyle** [comment]
One moment, caller ...

**Comment by kerimoyle** [comment]
https://cellml-specification-dev.readthedocs.io/_/downloads/en/i107_pagebreaks_in_pdf/pdf/

**Comment by agarny** [comment]
Looks nice. What about chapter 3?

**Comment by kerimoyle** [comment]
... there never have been breaks there ... do you want them too?

**Comment by agarny** [comment]
Consistency...? :)

**Comment by kerimoyle** [comment]
Reload it now?  I've added them in.

**Comment by agarny** [comment]
Yup, happy with it... at this point in time. :) Thanks. :)

**Comment by nickerso** [comment]
nice!

**Comment by kerimoyle** [comment]
Closed by #113
