### ISSUE TITLE
Replace grouping with simple encapsulation

### ISSUE THREAD

**Issue by nickerso** [cellml/cellml-specification#11]
Original tracker item: https://tracker.physiomeproject.org/show_bug.cgi?id=356

Draft implementation (in DocBook): https://github.com/A1kmm/cellml-core-spec/commit/b35c3e46b4de4631f9d6ed5fa2a5da33139525b5

libCellML issue: cellml/libcellml#29

I think this one has been completely agreed upon.

Summary
======

CellML 1.0 & 1.1
----------

```xml
<group>
  <relationship_ref relationship="encapsulation" />
  <component_ref name="parent">
    <component_ref name="child"/>
  </component_ref>
</group>
```

CellML 1.2
------

```xml
<encapsulation>
  <component_ref component="parent">
    <component_ref component="child"/>
  </component_ref>
</encapsulation>
```

**Comment by agarny** [comment]
Looks good to me.

**Comment by hsorby** [comment]
couldn't help myself:

child typo in CellML 1.2 encapsulation example

**Comment by nickerso** [comment]
corrected, thanks @hsorby

**Comment by nickerso** [comment]
This has now been completed in the google doc specification draft, so I think I can close this? Please reopen if anyone thinks it shouldn't be closed until the actual specification source is updated.
