### ISSUE TITLE
Can we ditch the "Specific element items" headings?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#110]
We have a plethora of decimal points in our headings (up to 6 in some places!).  In an effort to make the chapters more understandable, I'd like to remove the level 3 headings in Chapter 2, all of which are named "Specific information items".  There's nothing else on this level (ie: there is no 2.16.2) so we're essentially just adding (yet) another separator for no real reason ... ?

Thus, 2.16.1.1 would become 2.16.1 etc.

Currently we have this layout:

![image](https://user-images.githubusercontent.com/46887220/77867493-fb4b5a80-7293-11ea-96b5-aa6557290f12.png)

**Comment by agarny** [comment]
Sounds reasonable to me.

**Comment by kerimoyle** [comment]
On closer inspection I missed a bit ... but this is the only section written like this.  Can I:
- remove the section heading for 2.1.1 (to make consistent with all other sections), and
- remove the section heading for 2.1.2 (as initially proposed)

![image](https://user-images.githubusercontent.com/46887220/77867818-5d588f80-7295-11ea-90fe-6fd753e41640.png)

**Comment by agarny** [comment]
I would be ok with it. The current `2.1.1` could be considered as introductory text.

**Comment by kerimoyle** [comment]
Yep, just as in the other sections.  I'll do a mock up and see what others think

**Comment by nickerso** [comment]
sounds good to me.

**Comment by kerimoyle** [comment]
Closed by #112
