### ISSUE TITLE
Create single-page HTML of normative spec for namespace landing page

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#119]
We need something to live under the namespace URL, so will create a single-page version of the normative spec including:
- link to the PDF version
- information on where to find the informative one

**Comment by hsorby** [comment]
The title for the single page spec. is currently:
`Normative CellML 2.0 Specification`
Are people ok with this?

**Comment by hsorby** [comment]
PDF form of the normative spec. should be available at:
https://cellml/org/specifications/cellml_2.0/normative_cellml_2.0_specification.pdf

**Comment by hsorby** [comment]
The informative spec. can be found at:
https://cellml.org/specifications/cellml_2.0/informative_cellml_2.0_specification.html

**Comment by agarny** [comment]
> The title for the single page spec. is currently:
> `Normative CellML 2.0 Specification`
> Are people ok with this?

I am.

**Comment by nickerso** [comment]
just to be the odd one out, I'd go for `CellML 2.0 Normative Specification` - CellML 2.0 is the important part and I think should come first.

I would also expect the informative spec to be at https://cellml.org/specifications/cellml_2.0/informative/ - or do you mean a single page version of the informative specification?

**Comment by agarny** [comment]
> just to be the odd one out, I'd go for `CellML 2.0 Normative Specification` - CellML 2.0 is the important part and I think should come first.

Hmm... I see your point, but... normative and informative are adjectives, so grammatically speaking they really ought to be first...?

> I would also expect the informative spec to be at https://cellml.org/specifications/cellml_2.0/informative/ - or do you mean a single page version of the informative specification?

@kerimoyle to comment, but I would indeed expect several pages, so https://cellml.org/specifications/cellml_2.0/normative/ and https://cellml.org/specifications/cellml_2.0/informative/?

**Comment by nickerso** [comment]
> Hmm... I see your point, but... normative and informative are adjectives, so grammatically speaking they really ought to be first...?

Its a name, not a grammatically correct sentence :) but mostly when people download the file they will expect to see it under 'C' not some other word that they can't remember what it means. If you'd prefer, I was actually going to suggest a title like `CellML 2.0: Normative Specification` (and the corresponding `CellML 2.0: Informative Specification`).

**Comment by agarny** [comment]
For a title, the `:` would work for me, but what if we want to reference the normative/informative specification...?

**Comment by MichaelClerx** [comment]
You could either be formal and write "for blahblahblah see "CellML 2.0: Normative specification" or just write "for blahblahblah see the [normative specification](url goes here)" ?

**Comment by agarny** [comment]
Ok, happy with @MichaelClerx's suggestion and therefore with `:`.

**Comment by kerimoyle** [comment]
Personally, I like CellML 2.0: Normative Spec and CellML 2.0: Informative Spec.  It's clear, it's grammatical, and it places the entry where you'd look for it.
