### ISSUE TITLE
Should namespace URLs be https?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#128]
In 1.1 we have the namespaces for CellML and MathML ... since everything everywhere seems to be going to https, should these ones too, or does that change their meaning?

CellML 2.0 namespace: The namespace http://www.cellml.org/cellml/2.0#.

MathML namespace: The namespace http://www.w3.org/1998/Math/MathML.

**Comment by MichaelClerx** [comment]
No need for them to be https, their purpose is to be unique unchanging identifiers, not for visiting, so you don't gain anything by making them https

**Comment by MichaelClerx** [comment]
This guy says it changes the meaning: https://stackoverflow.com/questions/30707609/xml-namespace-uri-with-https

**Comment by kerimoyle** [comment]
Great, that's kind of what I figured, but wanted to check :) Thanks!

**Comment by agarny** [comment]
Also, FTR: https://github.com/cellml/libcellml/issues/452.

**Comment by nickerso** [comment]
I think we all agree to keep them as http.
