### ISSUE TITLE
Should we define comments in the spec?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#129]
See: https://cellml-specification-dev.readthedocs.io/en/update_to_cellml2/reference/formal_and_informative/specA2.html#semantically-equivalent-cellml-infosets

We talk about "comment information items" in 1.2.3.1.1 but don't define them anywhere?

**Comment by agarny** [comment]
I imagine that we are talking about an XML comment? If so, maybe this is the terminolgy we should be using, as well as link to https://www.w3.org/TR/2006/REC-xml11-20060816/#sec-comments?

**Comment by kerimoyle** [comment]
Yes, an XML comment.  Then a follow-on, should we also be defining the characters (or character combo) used to create comments (!, <, > etc) too in 1.1 Terminology?

**Comment by agarny** [comment]
Hmm, we probably ought to, I guess.

Otherwise, in 1.1 Terminology, the CellML 2.0 namespace is `http://www.cellml.org/cellml/2.0#`, but its link is to `http://www.cellml.org/cellml/2`...?

**Comment by kerimoyle** [comment]
Yeah, I know, it's fixed in my latest.

**Comment by MichaelClerx** [comment]
I'm pretty sure I brought up something about this in the google doc spec! There are 11 types of information item defined here https://www.w3.org/TR/xml-infoset/#infoitem (which we link to), and we designate 8 of them "specific". We're not really defining them just saying _of the 11 that exist_, we're going to now say something about these 8. And then we talk about the other 3 in veiled terms a bit, so I suggested at one point to make it more explicit...

**Comment by MichaelClerx** [comment]
I think my point was that the stuff about changing CellML without affecting was about the other 3 types.

Main takeaway here is that we don't _define_ any of the 11 types in the CellML spec, we refer to already defined things from the XML spec, so we don't need to define comment information items, but could link to https://www.w3.org/TR/xml-infoset/#infoitem again the first time they're mentioned maybe

**Comment by hsorby** [comment]
> but could link to https://www.w3.org/TR/xml-infoset/#infoitem again the first time they're mentioned maybe

I agree with this no need to define it, just reference it.

**Comment by nickerso** [comment]
agreed.
