### ISSUE TITLE
Do we need the xlink namespace for `href` in imports?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#13]
From the current spec:

> Every `import` element MUST contain an attribute information item in the namespace `http://www.w3.org/1999/xlink`, and with a local name equal to `href`. The value of this attribute SHALL be a valid locator `href`, as defined in section 5.4 of the XLink specification. The `href` attribute SHALL be treated according to the XLink specification, by applying the rules for simple-type elements.

It seems to me the last line makes this non-standard use of xlink? If we're doing that, then maybe it'd be less work* for everyone** to have an unprefixed href attribute whose value SHALL etc. Or is that impossible for parsers? @jonc125 ?

*turns `<import xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="Pandit_et_al_2001_endo.cellml">` into `<import href="Pandit_et_al_2001_endo.cellml">`

**introduces a CellML 1.1 incompatibility, so requires a few extra lines in the 2-to-1 XSLT. Imports aren't widely used, so minimal impact I'm guessing

**Comment by nickerso** [comment]
Reading https://www.w3.org/TR/xlink/#simple-links I think we are following the XLink spec correctly:

The XLink element for simple links is any element:
* with an attribute in the XLink namespace called type with a value of "simple" or
* with an attribute in the XLink namespace called href and no attribute in the XLink namespace called type. In this case, the value "simple" is implied for the type attribute.

making the `cellml:import` a simple-type element.

This follows the "use existing standards where possible" rule that we sometimes choose to follow :)
