### ISSUE TITLE
Can we demote singleton numbered sections?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#130]
We have a lot of sections which are only children ... this serves to add to the decimal point collection without giving any meaningful definition (there seems to be no relationship between the levels of decimal between sections)?  Can we demote points which are on their own?  
For example:
1.2.3.1 
1.2.4.1
1.2.6.1 ... and no doubt others could be removed?

**Comment by kerimoyle** [comment]
![image](https://user-images.githubusercontent.com/46887220/78071425-f7d1e380-73f9-11ea-990e-2100d28436b9.png)

**Comment by agarny** [comment]
I probably would, but maybe there was a rationale for it in the first place, @nickerso?

**Comment by hsorby** [comment]
I'm arguing for consistency reasons to keep it.

**Comment by agarny** [comment]
If so then there are other similar changes that would have to be undone?...

**Comment by hsorby** [comment]
To do with numbering?

**Comment by MichaelClerx** [comment]
Keep them in! This way we can add more rules later without breaking anything

Otherwise a 1.2.3. might have to become a 1.2.3.1 if we want to add a 1.2.3.2

**Comment by kerimoyle** [comment]
> To do with numbering?

Yes.  We recently removed the redundant (I thought ... ) .1 from all sections of Chapter 2.  See #110 and #112

**Comment by agarny** [comment]
> Keep them in! This way we can add more rules later without breaking anything
> 
> Otherwise a 1.2.3. might have to become a 1.2.3.1 if we want to add a 1.2.3.2 in CellML 2.1

Hmm... I (clearly) didn't think of that, but that is actually a very good and valid point for keeping them in.

**Comment by agarny** [comment]
> Keep them in! This way we can add more rules later without breaking anything
> 
> Otherwise a 1.2.3. might have to become a 1.2.3.1 if we want to add a 1.2.3.2 in CellML 2.1

Interestingly enough, we are already breaking that "rule". For example, for the `units` element, we are doing the right thing (see https://cellml-specification-dev.readthedocs.io/en/i119_namespace_landing_page/reference/formal_and_informative/specB08.html), but not for the `component` element (see https://cellml-specification-dev.readthedocs.io/en/i119_namespace_landing_page/reference/formal_and_informative/specB07.html).

**Comment by kerimoyle** [comment]
@agarny I don't understand?  The `units` are actually pretty wrong ... (indenting was messed up ...points 2-4 are not a subpoint of 1 ...) and points 1 and 2 need to be merged (see #135).  In what way is it "right"?

![image](https://user-images.githubusercontent.com/46887220/78177571-cff68480-74ba-11ea-9fca-8245e7ceab7e.png)

**Comment by agarny** [comment]
Sorry, typo at my end, I meant that for the `variable` element, we are doing the right thing (see https://cellml-specification-dev.readthedocs.io/en/i119_namespace_landing_page/reference/formal_and_informative/specB08.html), but not for the `component` element (see https://cellml-specification-dev.readthedocs.io/en/i119_namespace_landing_page/reference/formal_and_informative/specB07.html), as confirmed by the links.

**Comment by kerimoyle** [comment]
Sigh.  I get it ... but I can also see this creating massive chains of meaningless decimals "just in case" something changes later.  It's swapping readability now for possible future consistency.  Does this mean that people want to revert #112 again?

**Comment by agarny** [comment]
I don't think readability is too bad. I do, however, agree (and do find) that it looks odd to have only one item in some places. Otherwise, I am not sure we need to revert `reference/sectionB_elements.inc ` in #112. There, we only removed an unnecessary intermediate layer.

**Comment by MichaelClerx** [comment]
I'm happy with the changes in #112! You're right there has to be some cut off, somewhere, otherwise we'd have to 1.1.1.1.1.1.1.1.1 everything :D

**Comment by MichaelClerx** [comment]
So are we decided to keep #112 merged then, but to not remove further decimals at this point, so that this issue can be closed?

**Comment by kerimoyle** [comment]
It sounds like it, yes.

**Comment by agarny** [comment]
> So are we decided to keep #112 merged then, but to not remove further decimals at this point, so that this issue can be closed?

Yes from me.
