### ISSUE TITLE
Should 1.2.2.3 be moved into 1.2.3?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#131]
It seems that 1.2.2.3 belongs in 1.2.3 rather than in 1.2.2? Or do I add a link to "semantic interpretation" in 1.2.2.3 to the section below?

![image](https://user-images.githubusercontent.com/46887220/78076174-661aa400-7402-11ea-9ccf-9aba51bdab92.png)

**Comment by agarny** [comment]
I think that 1.2.2.3 is in the right place, but otherwise yes to a link.

**Comment by MichaelClerx** [comment]
I can see the case for it being in either place, maybe I'd lean slightly towards 1.2.3, as the rest of 1.2.2 is about what may and may not appear?

**Comment by kerimoyle** [comment]
I'd rather have it in 1.2.3 ... it just seems odd to have it in 1.2.2 where there is nothing else about semantic equivalence, and all about elements.

**Comment by hsorby** [comment]
I'd rather see it in 1.2.3 as it seems to be defining semantic equivalence with reference to specific information items.

**Comment by agarny** [comment]
1.2.3 it is then. :)

**Comment by kerimoyle** [comment]
Thanks, I'll move it.

**Comment by hsorby** [comment]
I do find it has an overlap with 1.2.3.1.2 as what is order change  other than a remove and an insert.

**Comment by MichaelClerx** [comment]
What does @nickerso think about this?

**Comment by nickerso** [comment]
1.2.3 is defining semantic equivalence, not semantic interpretation. 1.2.2.3 is the correct location in my opinion, as this is important for the spec in general not only when talking about semantic equivalence. 1.2.3.1.2 is only talking about namespaces, so the overlap with 1.2.2.3 is minimal if at all.

**Comment by kerimoyle** [comment]
@nickerso Can you explain the difference between semantic equivalence and interpretation?  I haven't got that clear yet ...?

**Comment by kerimoyle** [comment]
Actually, after sleep, I think I get it.  But (what I get ...) is still not consistent:

1.2.2 is talking about what will be interpreted as values or information in CellML.  And some things don't affect those values:
- whitespace (where appropriate)
- order of elements
- order of attributes
- comments

1.2.3 is talking about situations which don't change the interpretation between two models.  Of course this will be related to the points in 1.2.2 ...

... but if the point 1.2.2.3 re order being unimportant has a place in 1.2.2, then shouldn't there also be a statement there about whitespace?  Since it doesn't affect interpretation? ditto comments?

I don't mind where things end up, but I still can't quite get the rationale for splitting the kinds of definition between these two points?

**Comment by MichaelClerx** [comment]
I think you really need to read it in terms of the 11 types of information item defined in XML. Maybe this link: https://www.w3.org/TR/xml-infoset/ is slightly better than the one given in the spec, because it shows you the list of 11.

So there are 11 types of information item in XML, and the CellML spec calls 8 of those "specific" items, and 1.2.2 gives the special rules that apply to these 8.

Section 1.2.3 talkes about the other 3, starting with comment information items (2.7), then namespace information items (2.11), and finally character information items (2.6)

So it would make a lot of sense to me to call this section "Non-specific information items", so that it's clear that 1.2.2 and 1.2.3 cover CellML's rules for all 11 types together

**Comment by nickerso** [comment]
Yep, I think @MichaelClerx has it correct - 1.2.2 is saying these are the things covered in this spec, 1.2.3 is saying these are not covered in the spec, but in terms of determining semantic equivalence we don't care about these other information items.

I'm happy to re-title the section. Will add on top of #157..
