### ISSUE TITLE
Merge 2.5.1 and 2.5.2?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#135]
See below (ignore formatting, that's fixed already).  For variables and components the name uniqueness requirement is lumped in with the name definition in the first point.  Is there a reason that units are different?

![image](https://user-images.githubusercontent.com/46887220/78083834-20b2a280-7413-11ea-8246-e8c971f41077.png)

**Comment by hsorby** [comment]
Yes.

**Comment by kerimoyle** [comment]
Do we have a seconder? @agarny @MichaelClerx @nickerso ?

**Comment by agarny** [comment]
Indeed, I can't think of a reason for not merging them.

**Comment by kerimoyle** [comment]
Great, thanks.  I'll do that now.
