### ISSUE TITLE
Data representation of names in unicode is redundant?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#14]
Hi all
Just going through the draft 2.0 specifications and I wondered if  3.1.1.2 (Basic Latin alphanumeric and basic Latin underscores) was a subset of 3.1.1.1 (Unicode)?  Do we need them both, or is 3.1.1.2 as the more restrictive one sufficient?  It then affects the definition of 3.1.1.5 (comparing as identical sequeneces of Unicode).  Thoughts?
Go well,
Keri

**Comment by nickerso** [comment]
I think the 3.1.1.1 (Unicode) sets the context for identifiers and then the other rules restrict what can be used. @MichaelClerx has tidied up the language used in these section quite a bit, which I think makes it all a lot clearer.

**Comment by kerimoyle** [comment]
Thanks, I'll go through the newer doc in the morning.

**Comment by MichaelClerx** [comment]
Cool! Let me know if it's better/worse, still a work in progress in many ways :-)
