### ISSUE TITLE
Informative 3.8 math

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#141]
Write the "see more" block for this section.

**Comment by kerimoyle** [comment]
I'm having trouble understanding whether there are components in a model which would *not* be called "pertinent component elements"?  And if not, can we not just say "all the components in the model?" (where "model" obeys the importing rules re encapsulated children)?

![image](https://user-images.githubusercontent.com/46887220/78516062-5ccb7600-780c-11ea-8302-5649bd4727d8.png)

**Comment by nickerso** [comment]
This is ensuring that all components down the encapsulation hierarchy imported across potentially many models are pertinent. In the spec, `model` is an element in an XML document, here we are trying to define what makes up the mathematical model being encoded in CellML.

**Comment by MichaelClerx** [comment]
So 2 and 3 here are really defining the rules for imports! _That's_ where that section went!

Hmmmmm

**Comment by MichaelClerx** [comment]
Not sure that should be here, as the consequences stretch beyond maths (e.g. component references and variable references depend on 3.8.1.3)
