### ISSUE TITLE
3.4.2 confusing wording?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#149]
3.4.2 seems odd to me:
- is there ever a component reference which is _not_ a descendant of a model element? If not, why is this phrase there?
- should it perhaps be "direct descendant" instead?

![image](https://user-images.githubusercontent.com/46887220/78191441-80bc4e00-74d2-11ea-8bb7-146c729bf171.png)

**Comment by MichaelClerx** [comment]
Agreed! The text above makes it clear there are only 3 cases, so 3.4.2 should just say which of those cases it applies to, using the exact same wording

**Comment by nickerso** [comment]
I think this is something that has arisen now that the introductory paragraph is explicit in which elements/attributes are being covered in 3.4. So I think 3.4.2 can now be deleted.
