### ISSUE TITLE
Do we need to check for semantic equivalence where the difference is in a real number format?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#15]
See 2.2.1 Semantically equivalent CellML infosets.  Do we need to check for equivalence by comparing real number instances (in variable->initial_values, math->exponents, math->multipliers) as well as the other items listed? eg: exponent = 0.1 vs exponent = .10; or 1e-1 vs 0.1 etc

**Comment by nickerso** [comment]
good point, I think we do.

**Comment by MichaelClerx** [comment]
Not sure about this! I'm happy to say a model with "x = 1" is different from "x = 1.0". The CellML spec is mostly about syntax rather than meaning. We don't accept a model that says "x = 1" as equivalent to a model that says "1 = x" either (ultimately that would mean we need to decide if arbitrary mathematical statements hold to decide if a document is valid CellML)

**Comment by kerimoyle** [comment]
It only affects things like imports when elsewhere we say you can't
duplicate the model (or some component of it)?

**Comment by jonc125** [comment]
For those I think the same lexical representation of numbers would be OK and catch the errors we expect to catch (i.e. somehow ending up importing yourself - when the lexical representation would be the same by definition).

Otherwise you could say that the value space as defined by XML Schema has to match, which I think boils down to IEEE floating point equality tests.

**Comment by kerimoyle** [comment]
Agreed ... I think ... 
So just for my own clarity, when we don't allow models to import themselves it's to prevent a circular dependency in our references _rather_ than to prevent the actual situation of duplicated models existing?  

Is it possible for twins to exist (ie: importing identical models to a single parent?) If not allowed, then we need to test more than lexical representation.  If it's allowed, could there be a valid situation for the duplicated parent-child arrangement to occur, in which case, instead of forbidding it, do we want to simply create a new copied instance of the imported model at runtime to avoid the circular dependency?

**Comment by jonc125** [comment]
Indeed, it's to avoid circular imports (which could crash the library due to infinite recursion).

Importing identical models to the same parent (directly or indirectly) is fine, and I think actually quite standard to get multiple copies of the same component connected up in different ways.

**Comment by MichaelClerx** [comment]
I'm quite surprised that you all want to do this!  To see if e.g. 0.99999999999999999 is equivalent to 1 we have to interpret the meaning of the symbols, so it stops being a purely syntactical thing like the rest of the spec is

**Comment by MichaelClerx** [comment]
To do that in a software tool, I'd have to parse the text into a number, hope that that went perfectly (i.e. the format is exactly compatible with the language I'm programming in), and then hope that my language has excellent floating point comparison support

**Comment by MichaelClerx** [comment]
You could get different results depending on what type you used to represent numbers in your cellml handling code. Don't like this!

**Comment by kerimoyle** [comment]
It's only important if duplicate models were not permitted (but it sounds like they are - sorry, still getting my head around all this!).  If they are, we don't care about what the content of them *means* (ie: model A with a=1 is allowed to be the same as model B with a=0.999999999, etc).  Since there's no problem having duplicate models *existing*, that's fine, we don't need to do any awful float comparison.  It seems that the only issue is how the duplicate came to be there in the first place - and the only bit of that process is importing a model from itself.  If that process is something that people would find useful, then maybe it gets dealt with at runtime outside the specs here?

**Comment by kerimoyle** [comment]
Closing as is not an issue ... only relevant to the procedure for importing.
