### ISSUE TITLE
3.7 isn't actually saying anything?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#153]
The title "Effect of units on a variable" doesn't really match what appears in the text ... where nothing about the effect of units on a variable is mentioned ...?

![image](https://user-images.githubusercontent.com/46887220/78204247-9db64880-74f5-11ea-92c5-5138a4bdc9b2.png)

Maybe this is where we need to talk about mismatched multipliers ...? ... and/or something else? ... and/or change the title?

**Comment by MichaelClerx** [comment]
I don't mind this bit!
Do we mention anything related to this in the connections part?

**Comment by MichaelClerx** [comment]
Agreed the title is a bit vague. I guess the "effect" of the units attribute is that it imbues the variable with a "variable units" and a "variable unit reduction" property, which can then be used in other bits of the spec. The "See more" bit could definitely point out the relevant other bits to look at though (connections+unit conversion, maths+bad-units-are-allowed)

**Comment by nickerso** [comment]
I agree with @MichaelClerx's interpretation of the interpretation of the effect :) 

Shall close for now, but can reopen if this becomes an issue.

**Comment by kerimoyle** [comment]
Sorry, reopening ... I'm still grappling with this section.  I just don't see the point of it ... or if it is important in this form, why we don't have a similar section for references to all the other things that have references? eg: effect of component reference on a connection, effect of variable reference on a mapping etc.  All this is saying is that is should be valid (... but other references don't have to be?)

Could we:

- remove it altogether (my first vote!)
- move the point into the units reference section instead (my second vote!),
- remake this section into "Interpretation of `variable` elements", which it fits in a little better and allows us to discuss units and their effects properly?
- add similar points about valid references into the other "Interpretation of `something` element" sections ... which then also means creating an interpretation of component element section *just* for this.

In 3.2 we have:
![image](https://user-images.githubusercontent.com/46887220/78949070-8d6a2300-7b1e-11ea-8fbb-90fd9e51ba65.png)

**Comment by MichaelClerx** [comment]
>  eg: effect of component reference on a connection, effect of variable reference on a mapping etc. All this is saying is that is should be valid (... but other references don't have to be?)

It's not about references, it's about the idea that a variable "has" a unit

**Comment by kerimoyle** [comment]
Hmm.  Could we add/change a statement that explains whatever "having" a unit means (cf a valid reference to a units item?) I still don't get any info from this section ...

**Comment by MichaelClerx** [comment]
2.8 says:

> The units attribute. The value of the units attribute MUST be a valid CellML identifier, and MUST meet the constraints described in the Effect of units on variables section.

but could say

> The units attribute. The value of the units attribute MUST be a valid CellML identifier, and MUST be a valid units reference. 

And then the first sentence of 3.7 could go, making it

> ### 3.7. Effect of units on a variable
> 
> 1. The target of the units attribute on a variable is referred to as the variable units, and the corresponding unit reduction (see Interpretation of units) is referred to as the variable unit reduction.
