### ISSUE TITLE
List of required latex packages?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#154]
I've got a lot on my system already, so can't give a full list, but had to install

- latexmk
- fncychap
- tabulary 
- tocloft

to get the pdf docs to build

**Comment by hsorby** [comment]
These are all the packages that I had to install from a minimal installation of ``BasicTex`` on macOS (using the ``tlmgr`` application):

- latexmk
- fncychap
- titlesec
- tabulary
- varwidth
- framed
- wrapfig
- capt-of
- needspace
- tocloft
- textgreek
- babel-greek
- greek-fontenc
- cbfonts
- courier
- helvetic
- fontspec

Not sure if that last one helped me out. I also had to install some fonts for the ``xelatex`` that we use for UTF-8 support

- FreeSans
- FreeSerif
- FreeMono

**Comment by MichaelClerx** [comment]
Those fonts are in
- texlive-gnu-freefont
if you're using texlive

**Comment by MichaelClerx** [comment]
Should we incorporate this info into README.md ?

**Comment by agarny** [comment]
I guess it wouldn't harm. (I remember also having problems at the beginning and ended up installing everything from texlive.)
