### ISSUE TITLE
Import wording again, sorry

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#155]
> #. The imported infoset SHALL be considered holistically such that items relevant to the imported infoset (:code:`unit` children of imported :code:`units` elements or the :ref:`encapsulated set<specC_encapsulation_set>` of imported :code:`component` elements) are themselves available to that :code:`import` element child.

Can we leave out "holistically" here?

1. I find it very distracting, makes me think of reductionist vs holistic philosophies etc., nothing to do with spec
2. We _immediatly_ clarify what we mean by this term, and then never use it again, so see no point of introducing it?

**Comment by nickerso** [comment]
👍
