### ISSUE TITLE
Is the plus sign (U+002B) permitted in exponents?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#16]
I've been going through the number formats (3.5.4) and wanted to make sure I understand correctly:  When we have a real number in scientific notation, we do *not* permit the plus sign in front of the exponent?  ie:  100 = 1.0e+02 is not permitted, it must instead be 100=1.0e2 ?

**Comment by MichaelClerx** [comment]
Hi Keri. That does seem to be the case from the current spec, but I'd consider that a bug that needs addressing!

**Comment by kerimoyle** [comment]
I'm not sure if it's a bug really, perhaps just an over-enthusiastic restriction in the specs?  Will dig a bit more about how it's actually used in the code - there's no validation for any numbers that I've found so far.  Along the same lines, 3.5.5 could also be problematic:
"1.0E" and "1.0E-" will choke C++ (I think?) but are apparently permitted and interpreted as a zero exponent here?

**Comment by MichaelClerx** [comment]
I'm guessing there's an iso standard or something for this that we could follow. 

The code (libcellml?) _should_ eventually get some tests, as things like 12345678901234567801234567890123456780 are and should be valid CellML numbers, just like 9.99e1234567890123456780. Libcellml and other tools should notice that they can't handle this and tell the user

**Comment by kerimoyle** [comment]
There are some silent conversions happening in the parser using std::stod and std::stoi which allow the plus sign as I would have expected.  Also, later on we have:

`bool isCellMLExponent(const std::string &candidate)
{
	/// @cellml2_3 __TODO__ 3.5.4 Exponent string seems to allow the plus sign but it's forbidden in 3.5.4?
    if (candidate.length() > 0 && *candidate.begin() == '+') {
        return isCellMLInteger(candidate.substr(1));
    }
    return isCellMLInteger(candidate);
}`

... which strips the + out from exponents (though not elsewhere).  I haven't found a conversion for blank exponents (as in 3.5.5) yet.

**Comment by nickerso** [comment]
This has been corrected in the current draft. I suspect we need to make an updated draft available...
