### ISSUE TITLE
Make sure all versions of the spec are the same

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#163]
I'm getting a bit worried the automated parts of the spec can go out of sync between versions of the spec.

E.g., we need to check that we have same heading numbers in the

- normative PDF
- normative HTML
- normative HTML on the landing page
- informative HTML

Alternatively we can make our life a bit easier by dropping some of the versions? I'd be fine with having a single normative PDF document, without html versions

**Comment by kerimoyle** [comment]
It's a good point ... but all are build from the same "source" files (four big files, which are split to make the HTML parts), so they will be identical in content once the branches which we're looking at them from are merged etc :)

**Comment by nickerso** [comment]
I agree with @MichaelClerx, and we need to be careful. While the same source is being used, those source files are being assembled independently, so including things in a different order will result in different numbering of the sections, right?

The approach we are using is nice and flexible, we just need to be very careful about consistency and how these documents are managed going forward...

**Comment by hsorby** [comment]
I think @kerimoyle has struck a nice balance between flexibility on how we construct documentation and being able to construct documentation that has equivalent content (agnostic to format specifics) with a minimised danger of creating inconsistencies.

**Comment by kerimoyle** [comment]
The others are right though ... numbering needs to be watched.  It would be easy enough to skip a point during the include process, in which case all later numbers will be messed up.

**Comment by MichaelClerx** [comment]
We've done some good work on this, I think
