### ISSUE TITLE
19.10.9.2-3 Duplicates?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#17]
Is there a significance in the order of specification of mapped variables (ie: Variable A mapped to B is different from B mapped to A).  If not, do we need both of the paragraphs in 19.10.9.2 and .3?

> 19.10.9 The applicable interfaces for variables A and B SHALL be defined as follows.
> 1. When the parent component element of variable A is in the sibling set of the parent component element of variable B, the applicable interface for both variables A and B SHALL be the public interface.
> 2. When the parent component element of variable A is in the encapsulated set of the parent component element of variable B, the applicable interface for variable A SHALL be the public interface, and the applicable interface for variable B SHALL be the private interface.
> 3. When the parent component element of variable B is in the encapsulated set of the parent component element of variable A, the applicable interface for variable A SHALL be the private interface, and the applicable interface for variable B SHALL be the public interface.

**Comment by jonc125** [comment]
There's no significance mathematically, but there is syntactically in that one is called A and one is called B. So if there's a parent/child relationship between the components you need to know which is which to determine which interface to use for each.

**Comment by kerimoyle** [comment]
OK, thanks :)
