### ISSUE TITLE
3.10 language: network vs set?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#170]
Should we use different terminology to describe the "variable equivalence network"?  
Pros of "network": it implies connectivity requirements, which makes the language around interfaces and connections more straightforward;
Cons of "network": it's not really true, it's more of a set (in the end)?

**Comment by MichaelClerx** [comment]
I thought the idea was that the network is for all variables in the model? So a graph where each node is a variable, and then and edge is added for each connection, and finally starting from variable X, any variable Y you can reach by travelling over the edges is part of X's connected variable set?

**Comment by MichaelClerx** [comment]
I agree this is a bit cumbersome :D

**Comment by kerimoyle** [comment]
Agreed -  I think.  So there is a _global_ variable _network_ (connected by maths) but _equivalent_ variable _sets_ (connected by mapping)?

**Comment by kerimoyle** [comment]
The second sentence of 1) doesn't fit with that though ...

> For the purposes of this specification, the variable equivalence (conceptual) network SHALL be an undirected graph with one node for every variable element in the CellML model. **The arcs of this graph SHALL be equivalences defined in the CellML model.**

Oh dear, I've confused myself again.  Sigh.

**Comment by kerimoyle** [comment]
And the last point says:

> The `variable` elements in a CellML model SHALL be treated as belonging to a single "connected variable set".  Each set of connected variables is the set of all `variable` elements for which the corresponding nodes in the variable equivalence network form a connected subgraph.  Each set of connected variables represents one variable in the underlying mathematical model.

I don't understand the first sentence?  We start by saying there is a single connected variable set, then in the next sentence say that there are lots of them ...?  I know that all the variables are connected through the maths, but we haven't mentioned that anywhere here ... Can we change the first sentence so that either specifies the maths connection explicitly, or at least doesn't imply that they're all "connected" via the same mechanism?

**Comment by MichaelClerx** [comment]
> The second sentence of 1) doesn't fit with that though ...
> 
> > For the purposes of this specification, the variable equivalence (conceptual) network SHALL be an undirected graph with one node for every variable element in the CellML model. **The arcs of this graph SHALL be equivalences defined in the CellML model.**
> 
> Oh dear, I've confused myself again. Sigh.

Good catch. I think "equivalences" should be connections there. We have an arc from x1 to x2 if they are directly connected, but not an arc from x1 to every variable in its connected variable set!

**Comment by MichaelClerx** [comment]
> And the last point says:
> 
> > The `variable` elements in a CellML model SHALL be treated as belonging to a single "connected variable set".  Each set of connected variables is the set of all `variable` elements for which the corresponding nodes in the variable equivalence network form a connected subgraph.  Each set of connected variables represents one variable in the underlying mathematical model.
> 
> I don't understand the first sentence? We start by saying there is a single connected variable set, then in the next sentence say that there are lots of them ...? I know that all the variables are connected through the maths, but we haven't mentioned that anywhere here ... Can we change the first sentence so that either specifies the maths connection explicitly, or at least doesn't imply that they're all "connected" via the same mechanism?

I think we mean "Each varariable element in a CellML model SHALL be treated as belonging to a single "connected variable set"".
There are lots of sets, but each variable belongs to only one of them

We're not talking about maths here, just about connection+map_variables connections!

**Comment by kerimoyle** [comment]
> I think we mean "Each variable element in a CellML model SHALL be treated as belonging to a single "connected variable set"". There are lots of sets, but each variable belongs to only one of them.

That makes a WHOLE lot more sense!
