### ISSUE TITLE
3.10.9.2-3: rewording??

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#173]
Currently we have this: (see https://cellml-specification-dev.readthedocs.io/en/i143_3_10_map_variables_informative/reference/formal_and_informative/specC10_interpretation_of_map_variables.html)

> 9. The applicable interfaces for variables A and B SHALL be defined as follows.
> 9.1 When the parent component element of variable A is in the sibling set of the parent component element of variable B, the applicable interface for both variables A and B SHALL be the public interface.
> 9.2 When the parent component element of variable A is in the encapsulated set of the parent component element of variable B, the applicable interface for variable A SHALL be the public interface, and the applicable interface for variable B SHALL be the private interface.
> 9.3 When the parent component element of variable B is in the encapsulated set of the parent component element of variable A, the applicable interface for variable A SHALL be the private interface, and the applicable interface for variable B SHALL be the public interface.

a) I also think that the language here is really dense, and we could do with defining a component AA and component BB (instead of having to say "the parent component element of variable A" etc) to make it easier to explain?
b) It's been explained (I think) to me before, but reading it again I still feel that points 2 and 3 are identical??

Here's my suggestion for rewording:

1. When component AA and BB are sibling components, the applicable interface for all variables in both components SHALL be the public interface.
2. When component AA is a parent of component BB, the applicable interface value for all variables in AA SHALL be the private interface, and the applicable interface for all variables in BB SHALL be the public interface.

**Comment by MichaelClerx** [comment]
I would agree with that. We really don't need all these sibling sets etc. just to make this point!

- same parent? public-public
- parent-child? public-private
- anything else? can't be connected
