### ISSUE TITLE
Mapping vs connection wording?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#176]
Should we be consistent about calling equivalent variables "mapped" (as they're formed form `map_variables` elements) and components "connected" (as they're formed from `connection` elements)?

**Comment by MichaelClerx** [comment]
Hmmmm!

To me, the connection is between the variables, and the `<connection>` and `<map_variables>` elements are just a way we specify the details of these connections.

But going from the spec alone I see no reason you couldn't think of them as connections between components, within which lives mappings of variables...

I'd be careful to write from the second point of view, as I don't think that's what we intended in the rest of the doc, so it could lead to inconsistencies

Historically, in CellML 1 we had `<connection><map_components c1 c2 /><map_variables v1 v2 /></connection>` which perhaps made it clearer that we were specifying connections using a combination of `<map_x>` elements? In CellML 2 that's become `<connection c1 c2><map_variables v1 v2 /></connection>` which is shorter, but is not intended to imply there's some of of connection between components first, and some kind of further mapping between variables secondly. You can't have a connection without a map_variables, for example

**Comment by kerimoyle** [comment]
In meeting on 12.4.20 decided to change "mapped/connected variables" to "equivalent variables".
