### ISSUE TITLE
19.3.1.1 Prefix is double or integer?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#18]
Hi all

Is this a mismatch between the specs and the code?  Integer vs double for prefix of unit?

> 19.3.1.1: The prefix term is a conceptual property of unit elements. If the unit element does not have a prefix attribute information item, the prefix term SHALL have value 0.0. If the prefix attribute information item has a value which is an **integer string**, then the value of the prefix term SHALL be the numerical value of that string. Otherwise, the prefix attribute information item MUST have a value taken from the ‘Name’ column of the Prefix values table, and the prefix term SHALL have the value taken from the ‘Value’ column of the same row.

```
void Units::addUnit(const std::string &reference, const std::string &prefix, double exponent,
                    double multiplier, const std::string &id)
{
    Unit u;
    u.mReference = reference;
    // Allow all nonzero user-specified prefixes
    try
    {
        double prefixDouble = std::stod(prefix);      //<<<<<<<<<<<<<<<<<<<<<<<<
        if (prefixDouble != 0.0) {
            u.mPrefix = prefix;
        }
    } catch (std::invalid_argument&) {
        u.mPrefix = prefix;
    } catch (std::out_of_range&) {
        u.mPrefix = prefix;
    }
... etc ...
```

**Comment by agarny** [comment]
I would indeed say that there is a mismatch. For me a prefix must be an integer (I don't think that anything else would make sense?). So, yes, I would "fix" the code and also the specs: _"If the unit element does not have a prefix attribute information item, the prefix term SHALL have value **0**."_

**Comment by nickerso** [comment]
I think this is a case of the spec changing and libCellML not being updated to match. See cellml/libcellml#86 for when it used to be defined as a real value (even in COR!)

**Comment by agarny** [comment]
> I think this is a case of the spec changing and libCellML not being updated to match. See cellml/libcellml#86 for when it used to be defined as a real value (even in COR!)

Sorry, we clearly want to keep the prefix as a string. Personally (and I believe @kerimoyle too?), I was just talking about the test, i.e. I would have:

```
int prefixInt = std::stoi(prefix);
if (prefixInt != 0) {
    u.mPrefix = prefix;
}
```

rather than:

```
double prefixDouble = std::stod(prefix);
if (prefixDouble != 0.0) {
    u.mPrefix = prefix;
}
```

**Comment by kerimoyle** [comment]
Yes and no.  The change I'd like is as @nickerso suggested that it's read either as a string or an integer - this is in the parser not the test suite.  And the change that @agarny wrote is all that's needed :)  I'll do that today.
