### ISSUE TITLE
Real number strings must include basic real number strings

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#183]
> 5. A real number string:
>    1. SHALL be a base 10 representation of a real number r = s × 10 e where s is the significand, a real number, and e is the exponent, an integer.
>    2. The representation of the number SHALL be the representation of the significand followed immediately by the representation of the exponent.
>    3. The significand SHALL be represented as a basic real number string.
>    4. An exponent SHALL be represented by an exponent separator character, followed by the integer string representation of the value of the exponent. Non-negative exponents MAY begin with the Basic Latin plus sign character U+002B as the sign indicator. The exponent separator character SHALL be either the Basic Latin “E” character U+0045 or the Basic Latin “e” character U+0065.
>    5. A real number string without an exponent SHALL be a basic real number string.

This bit:

> The representation of the number SHALL be the representation of the significand followed immediately by the representation of the exponent.

says that you _have_ to have a "representation of the exponent".
That would be OK if "" was a valid representation of an exponent, but points 4 and 5 don't seem to allow that.

Two things I'd like to see resolved:

- it needs to be clear that the "real number string" concept includes a "basic real number string". So if we say a "real number string" is required it does _not_ mean you need an "e" or "E" in there. Point 5 seems to say the opposite.
- what about the case "1.2e"?

**Comment by kerimoyle** [comment]
Two things I'd like to see resolved:

> - it needs to be clear that the "real number string" concept includes a "basic real number string". So if we say a "real number string" is required it does not mean you need an "e" or "E" in there. Point 5 seems to say the opposite.

v. "A real number string without an exponent SHALL be a basic real number string." ?

> - what about the case "1.2e"?

Point 5 comes after point 4, which says "exponent SHALL be represented by an exponent separator character, followed by the integer string representation of the value of the exponent."  So 1.2e isn't valid because there is no integer string representation of the value of the exponent (it should be 1 when the number is blank, so would be 1.2e1, which is valid).

**Comment by MichaelClerx** [comment]
Both of these are fixed in #199
