### ISSUE TITLE
Import element: do we need a rule that says the URI must point to a CellML document?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#184]
Doesn't seem to say that at the moment, just that it must be a valid xref locator

**Comment by MichaelClerx** [comment]
This is the closest we get:

> When describing an import element or one of its children, the phrase “imported CellML infoset” SHALL refer to the CellML infoset obtained by parsing the document referenced by the href attribute.

is that enough?

**Comment by kerimoyle** [comment]
I think that the phrase "parsing the document" is enough to cover the case if there is no document, there will be no information ...?

**Comment by MichaelClerx** [comment]
ok!
