### ISSUE TITLE
Interpretation of imports, again.

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#187]
> The imported infoset SHALL be considered such that items relevant to the imported infoset (**unit children of imported units elements** or **the encapsulated set of imported component elements**) are themselves available to that import element child.

This text doesn't mention units used by the imported components

**Comment by MichaelClerx** [comment]
Maybe we can split this point, 3.1.2, into two points: one saying that units references are to be interpreted w.r.t. to parent model, and a second point saying that encapsulated components are also imported

**Comment by MichaelClerx** [comment]
Also, I can kiiiiinda see now how we thought only the first point was enough, so maybe the 2nd (and possibly 3d) point should be sub-points of the first? or the first can just go?

**Comment by MichaelClerx** [comment]
I still find this section hard to read!

I'm trying to summarise it for myself, just to see if I understand it (and if it makes sense). This is the best I've been able to do so far:

> 3.1.1 An imported `units` or `component` should be interpreted in the context of its parent model.
> 3.1.2 Unit references in imported `units` or `components` elements should be interpreted in terms of their parent model.
> 3.1.2 However, units referenced by imported elements, but not explicitly imported themselves, remain unavailable to the importing model.
> 3.1.2 If an imported component is part of an encapsulation hierarchy, then all its child components and any connections to child component variables remain intact. This rule applies recursively.
> 3.1.2 Connections to any sibling components of an imported component are broken.

I'm not thinking that:

- 3.1.1 can go, in favour of a more explicit statement of what that means (e.g. the stuff I have as 3.1.2 above)
- 3.1.1 might actually be invalid? because "interpreting" a component could well mean looking at the encapsulation hierarchy and seeing its connected to siblings, or has a parent, and these would then be imported too, just like child components (because why would they be different?)

**Comment by MichaelClerx** [comment]
I'm not sure if we need a rule saying you can't reference imported child components, because you can never reference child components outside of the context of the parent component anyway.
However, without such a rule maybe I could import a component, and then create new connections between it and its child components?

**Comment by kerimoyle** [comment]
> 3.1.1 might actually be invalid? because "interpreting" a component could well mean looking at the encapsulation hierarchy and seeing its connected to siblings, or has a parent, and these would then be imported too, just like child components (because why would they be different?)

It was my understanding that encapsulation was mean to do just that - to provide the single package that could be passed around the place.  Where sibling connections which are required for the component to function are broken by imports, it's a symptom that the encapsulation isn't doing its job: an additional component should be wrapped around those siblings so that they're imported together.  For encapsulation to be modular, it has to have boundaries somewhere ...?

**Comment by MichaelClerx** [comment]
> > 3.1.1 might actually be invalid? because "interpreting" a component could well mean looking at the encapsulation hierarchy and seeing its connected to siblings, or has a parent, and these would then be imported too, just like child components (because why would they be different?)
> 
> It was my understanding that encapsulation was mean to do just that - to provide the single package that could be passed around the place. Where sibling connections which are required for the component to function are broken by imports, it's a symptom that the encapsulation isn't doing its job: an additional component should be wrapped around those siblings so that they're imported together. For encapsulation to be modular, it has to have boundaries somewhere ...?

Still though, if you have a component A with children, connected to a component B with children, it wouldn't make sense for them not to be connected somehow. Otherwise you'd have two disjoint systems of equations in the same file

**Comment by kerimoyle** [comment]
A and B can be ... but not their children...? I think I'm missing your point somewhere?
