### ISSUE TITLE
19.3.1.4 Interpretation of multiplier and prefix seems strange?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#19]
Hi all
I've been checking the units equivalence for mapped variables, am confused by the equation given in the specs :

![image](https://user-images.githubusercontent.com/46887220/57462997-3870bd80-727a-11e9-94e9-d49f4e5f1552.png)

Say I have three variables whose units should be equivalent (including in multiplier/prefix, not just the cubic metre unit).
```
// u1 has units of (metres^3)
// addUnit has arguments of (reference, prefix, exponent, multiplier)
    u1->setName("m3");
    u1->addUnit("metre", 0, 3.0, 1.0);

// u2 has units of (1000)(L) 
    u2->setName("L1000");
    u2->addUnit("litre", 0, 1.0, 1000.0);

// u3 has units of (10^9)(mm^3)
    u3->setName("billion_mm_cubed");
    u3->addUnit("metre",-3, 3.0, 10e9);   // same as saying u3->addUnit("metre", "milli", 3.0, 10e9);
```

According to the formula though, the effect of the prefix and exponent terms of the u3 will be interpreted as 10^(p^e) or 10^(-3^3) = 10e-27 ... which does not cancel with the real multiplier of 10^9.

Should the formula be changed to include exponents of 10 in the denominator of (p*e) rather than (p^e) ... or maybe some brackets so (10^p)^e? ... or am I missing something?  Thanks :)

**Comment by agarny** [comment]
> According to the formula though, the effect of the prefix and exponent terms of the u3 will be interpreted as 10^(p^e) or 10^(-3^3) = 10e-27 ... which does not cancel with the real multiplier of 10^9.
> 
> Should the formula be changed to include exponents of 10 in the denominator of (p*e) rather than (p^e) ... or maybe some brackets so (10^p)^e? ... or am I missing something? Thanks :)

You are correct, the formula is wrong (once again). Personally, I would go with `(10^p)^e` (that's how I wrote it down on paper when "expanding" your unit definitions), i.e. something like:

<img width="582" alt="Screen Shot 2019-05-10 at 10 11 19" src="https://user-images.githubusercontent.com/602265/57490046-1293f900-730c-11e9-80ff-e9366e9afb2d.png">

(I must confess that I find that `x[u_x]` equation rather confusing, but it might just be me...?!)

**Comment by agarny** [comment]
As agreed, I have just double checked the equation and, as far as I am concerned, the equation in https://github.com/cellml/cellml-specification/issues/19#issuecomment-491087016 is the correct one for me. (So, I was definitely right to upvote myself! 🙂)

**Comment by kerimoyle** [comment]
Thanks for the doublecheck @agarny - I'll use this one now.

**Comment by MichaelClerx** [comment]
Is this copied over from the 1.0/1.1 specs? If so @jonc125 might have something to say about it?

**Comment by jonc125** [comment]
Yeah, @agarny 's bracketing is correct.

Personally I always stick a few examples in these equations to check they do the right thing!
