### ISSUE TITLE
How about `<variable name="x" initial_value="x" />`

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#190]
Is this one allowed?

**Comment by kerimoyle** [comment]
It's not forbidden, but would be the valid-but-nonsense category?  I'd guess it's a tighter cyclical reference than in the first example in informative spec: https://cellml-specification-dev.readthedocs.io/en/update_to_cellml2/reference/formal_and_informative/specC06_interpretation_of_initial_values.html
