### ISSUE TITLE
Reset interpretation: should we give the full algorithm we worked out?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#198]
I'm not 100% sure the definition makes sense without it, e.g.  the "considering sequentially" is restarted after a reset occurs, in our current suggested interpretation

**Comment by kerimoyle** [comment]
I think that's a great idea.  Not sure whether it would go in the informative or the normative stuff though? It kinda belongs in the normative, but might be hard to describe without an example ...?

**Comment by MichaelClerx** [comment]
Discussion said: No. Let's leave this as it is for now, see what people make of it, fix in 2.1 if required
