### ISSUE TITLE
Rename "when" to "trigger" (or some other noun)? 

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#20]
I've been working on the validation for resets and whens, and there's a lot of strange language in the error messages that could be made much easier to understand if we renamed the "whens" to something less weird, maybe "triggers" or similar?  All our other entities are named as nouns, and it makes the language around "whens" difficult to wrangle.

A global search-and-replace through the documentation and code would be fairly straightforward ... ?  Thoughts?

**Comment by agarny** [comment]
I have never been a fan of `when`'s, so I would certainly not mind if we were to use a different terminology.

**Comment by kerimoyle** [comment]
Closing as not needed in new spec :)
