### ISSUE TITLE
Deka prefix in units should be deca?

### ISSUE THREAD

**Issue by nickerso** [cellml/cellml-specification#21]
As per discussion in cellml/libcellml#327, it has recently been pointed out the the spelling of the `deka` prefix in the specification is the "American" spelling of this, whereas `deca` is the international spelling as used by the International Bureau of Weights and Measures.

We need to decide how to resolve this. Potential solutions are:

1. this is not an error, nothing needs to change
2. this is an error that should be fixed in CellML 2.0 and we switch to the international spelling `deca`
3. we should support both `deca` and `deka` prefixes.

**Comment by nickerso** [comment]
my preference is to leave it as it is, it is only in implementing libCellML that this issue has arisen - we have never had a user ask for the addition of `deca` to the spec. I would be against having both versions in the specification. And I'm on the fence about switching to `deca`.

**Comment by MichaelClerx** [comment]
I'm a fan of 3, with 'deka' being a deprecated alias of deca

**Comment by MichaelClerx** [comment]
Also worth pointing out that nobody uses deca/deka in their models, as far as I'm aware

**Comment by agarny** [comment]
Well, the [official SI prefixes](https://www.bipm.org/en/measurement-units/#si-prefixes) says it's `deca`. So, that settles it for me: option 2.

**Comment by hsorby** [comment]
I have to go with @agarny: option 2 for me.

**Comment by kerimoyle** [comment]
The best argument I can find against 2 (sorry @agarny and @hsorby) is that we allow alternate American spelling aliases for meter/metre and liter/litre, so for consistency should also allow alternate spellings in the prefix too.  The argument against that (sorry @MichaelClerx) is that the sequence below will give different behaviour between units and prefixes, which is then not consistent:
```
parse model (units of "deka"+"meter")
print model (units become "deca"+"meter")
```
The difference is only because I've added numbers to the prefix enums, which means that the `deka->10->deca` behaviour happens.  See [this branch](https://github.com/cellml/libcellml/compare/develop...kerimoyle:add_support_for_deka). 

If the numbers are removed from the enum we can keep both `deca` and `deka`, as we do absolutely no prefix/multiplier checking in libcellml, but have the same issues as earlier where users in different bindings could give silent differences in magnitude which are quite significant.  

Overall, am happy to go either way as it's clear both are compromises :)

**Comment by MichaelClerx** [comment]
I'm ok with option 2 as well.

9 deca% ok

**Comment by agarny** [comment]
Ok, I had to check...

Right now, the CellML 2.0 specification allows for `metre`/`meter`, `litre`/`liter` and `deka` (but not `deca` indeed). However, the [SI brochure](https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9-EN.pdf) only references `metre`, `litre` and `deca`, i.e. neither `meter` nor `liter` are listed as allowed alternatives for `metre` and `litre`, respectively.

Page 124 does acknowledge the existence of spelling variations, but they also mention that they follow the [ISO/IEC 80000 series Quantities and units](https://www.iso.org/standard/30669.html).

So, it seems to me that we should allow either:
- `metre`/`meter`, `litre`/`liter` and `deca`/`deka`; or
- `metre`, `litre` and `deca` only.

Personally, I am in favour of the second option. Indeed, CellML claims to be a standard. Now, it happens to rely on other standards. So, if anything, it really ought to respect those standards.

**Comment by hsorby** [comment]
I love the idea of following a standard.

 * `metre`, `litre`, and `deca` for me

**Comment by kerimoyle** [comment]
Happy with either option as long as we're consistent :)

**Comment by MichaelClerx** [comment]
> I love the idea of following a standard.

Me too, but I do worry about alienating users. So would be happier to have metre/litre/deca as the official ones - and the only ones we output in e.g. libcellml - but to be nice to model writers and accept the alternative spellings...

Feel free to override me though :D

**Comment by nickerso** [comment]
OK, so sounds like we all agree that the specification follow the SI definitions. Interesting to note that the latest version of SBML seems to have also removed meter/liter (not sure when that happened). I will email cellml-discussion to suggest we are, henceforth, strictly following the core SI units names and prefixes to see if there are any objections.

How libCellML handles this can be discussed over at cellml/libcellml#327.

**Comment by kerimoyle** [comment]
@nickerso Just a nudge - anything come from your survey of the users? Are we good to remove these alternatives yet?

**Comment by nickerso** [comment]
No objections, we're good to remove them.

**Comment by MichaelClerx** [comment]
Verging on the ridiculous, but if we've got metre and litre, should we have a <maths> instead of a <math> ? It does still contain MathML, not MathsML

**Comment by agarny** [comment]
As you said... :)

**Comment by kerimoyle** [comment]
I'd vote for <maths> :) ... but then I'd also vote for anything except our current Units and Unit combo which is frighteningly hard to write about, and instal with one L, and all the rest of it ...

**Comment by MichaelClerx** [comment]
Instal with one l ?

**Comment by agarny** [comment]
https://www.merriam-webster.com/dictionary/instal

**Comment by kerimoyle** [comment]
Strange but true ...

**Comment by MichaelClerx** [comment]
> our current Units and Unit

I've been calling them a "units definition" and then (but only informally) a "unit row"

**Comment by nickerso** [comment]
just to get back on topic - `<math>` is a MathML element which *must* be used (https://developer.mozilla.org/en-US/docs/Web/MathML/Element/math). Its in the MathML namespace and we have no control over it.

**Comment by MichaelClerx** [comment]
Cool!
Shall we close this issue?
