### ISSUE TITLE
Fix all external links

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#214]
- [x] Stuff is getting appended where it shouldn't be
- [x] Two links to infoset (in sectionA_definitions) should be moved to config file
- [x] Links to informative spec in preamble should be in config file
- [x] Decision re dated or canonical URL for references and display

**Comment by kerimoyle** [comment]
We have different addresses for the infoset links:

https://www.w3.org/TR/2004/REC-xml-infoset-20040204/
https://www.w3.org/TR/xml-infoset/

... which one is better?

**Comment by kerimoyle** [comment]
Ditto namespaces: 
https://www.w3.org/TR/2006/REC-xml-names11-20060816/ 
https://www.w3.org/TR/xml-names11/ 

And MathML2: 
http://www.w3.org/TR/2003/REC-MathML2-20031021/
https://www.w3.org/TR/MathML2/

**Comment by kerimoyle** [comment]
Xlink: 
https://www.w3.org/TR/xlink11/
http://www.w3.org/TR/2001/REC-xlink-20010627

**Comment by MichaelClerx** [comment]
They seem to start with

> This version:
>     http://www.w3.org/TR/2004/REC-xml-infoset-20040204 
> Latest version:
>     http://www.w3.org/TR/xml-infoset 

but not sure that helps?

Maybe the w3c is a slower glacier than even CellML, so the latest version will be "the same but worded better"

But maybe we should play safe and just go for the one that we can see right now?

**Comment by kerimoyle** [comment]
I should have asked the question better! There are three types of references:

- Those hardcoded in the text, intended for full display, eg in namespaces: do we want to **display** in the text the latest or the dated URL?
- Those in the reference section at the end: do we want to **display** in the references the latest or the dated URL (answered in part in #123)
- Those which are the underlying clickable links, where the URL is not displayed: do we want to **send** people to the latest or the dated URL?

**Comment by MichaelClerx** [comment]
I'd say the same for all three, to avoid confusion.

And leaning towards dated for all three.

Also just leaning in general. Goodnight!

**Comment by agarny** [comment]
Agreed that the URL should be the same in all three cases.

Re dated vs non-dated URLs, I like short URLs, but... my preference would still be for dated URLs, so as to "protect" ourselves against future potential changes that might break things for us.

**Comment by kerimoyle** [comment]
> Re dated vs non-dated URLs, I like short URLs, but... my preference would still be for dated URLs, so as to "protect" ourselves against future potential changes that might break things for us.

Just double checking, because we've been here already with #127 ? see https://github.com/cellml/cellml-specification/pull/127#issuecomment-607474889 ?  This means that now we'd list the full dated URL everywhere, cf the canonical one that is there now.  @nickerso ... you had thoughts earlier ...?
