### ISSUE TITLE
It'd be nice if there was some way to specify the order of the state variables

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#22]
To compare with other implementations

**Comment by nickerso** [comment]
Is this not defined (implied?) by the math? or do you mean the sequence of evaluation rather than the order of the ODE/DAE variables? In either case, doesn't seem like something that would be needed in CellML - but potentially something to consider as part of the libCellML API.

**Comment by MichaelClerx** [comment]
No the order of the variables in the state vector

**Comment by hsorby** [comment]
I think this is something that would belong on the libCellML issues list.

**Comment by MichaelClerx** [comment]
But how will libCellML know what the order should be?

**Comment by MichaelClerx** [comment]
I'm guessing this should be done with annotations, or some other user-specified non-core-cellml thing. Especially if we're going to have a canonical model form etc.
