### ISSUE TITLE
Ordering of sections in chapter 2 (elements)

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#221]
@agarny said: 

> Move 2.12 (`math` element) to 2.9, i.e. before `reset` element? It's just that we can perfectly have a model without resets, so the `reset` & Co. elements should be considered as "add-ons" and I would thefeore expect them to come after the `math` element.

and other similar criticisms can be made.

Is the order of the elements in section B something we wish to consider and possibly change at this time?

**Comment by MichaelClerx** [comment]
Ideally it'd be sort of related to the ordering in section C (#206), I suppose.

(Although not every element maps onto a concept, so not a perfect mapping)

**Comment by kerimoyle** [comment]
I'd be ok with changing the order.  I've always found it odd to have such an abstract idea as imports at the beginning, when you don't even know what you're importing ... 
How about (items in brackets are unneeded for a model to work)
model
component
variable
maths
(units)
(encapsulation)
(connection)
(map_variables)
(imports)
(import components)
(import units)
(resets)

**Comment by agarny** [comment]
When it comes to imports, I think  of them as being some kind of `#include`s. So, they come first in 99% of cases. So, yes, I am not keen on @kerimoyle's suggested order. :)

**Comment by kerimoyle** [comment]
But this is not describing the structure of your CellML file, it's describing how someone wanting to understand CellML syntax might read it best? How can you explain imports before explaining components or units (or encapsulation)?

**Comment by agarny** [comment]
We are talking about Chapter 2. So, there is nothing to explain here, just to state. This aside, the whole idea of a document with hyperlinks is that you can jump to a given section, if needed. Anyway... :)

**Comment by MichaelClerx** [comment]
I'd like imports to be right at the end

But I'd like it even more to just close this issue :D

**Comment by MichaelClerx** [comment]
Agreed we don't agree on a good order and closing this
