### ISSUE TITLE
Units in and out of operators

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#229]
In CellML 1.0/1.1 we had a nice (but incomplete) list of what units went in and came out of each MathML operator in the CellML subset. I'd quite like to have this back in the informative spec, as it's something implementers are always confronted with.

**Comment by kerimoyle** [comment]
I'm not quite sure I follow what you mean...?
Is it something like `a [volt] <times> b [metre] = c [volt.metre]` ? or something a little more sophisticated ...? If you can send me a link to the previous section you mean, I'll have a go ... I've scanned through https://www.cellml.org/specifications/cellml_1.1/ but don't reeeeaaaalllly want to read it in detail if you have something handy :)

**Comment by MichaelClerx** [comment]
Like [this](https://www.cellml.org/specifications/cellml_1.1/#sec_units_rules_applying_operators_to_units_definitions) but better

**Comment by kerimoyle** [comment]
Ah, ok, thanks.  "Better" means ... ?

**Comment by MichaelClerx** [comment]
- No `cellml:boolean` nonsense, (boolean is a type, not a unit)
- Specifying expected/allowed units into functions as well as out of them (sin(4 [V]) is not a thing)
- Updated to cover the new MathML subset

**Comment by kerimoyle** [comment]
@MichaelClerx  Where do you think this should sit? An extra section inside 3.8.3? or somewhere on its own? or ...?
https://cellml-specification-dev.readthedocs.io/en/i141_infomative_3_8_maths/reference/formal_and_informative/specC08_interpretation_of_mathematics.html

**Comment by MichaelClerx** [comment]
Up to you as long as it goes in somewhere! :D
