### ISSUE TITLE
Latex: interal links not in italics?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#242]
Currently internal links are rendered in italics, we'd probably prefer something else in the PDF

**Comment by MichaelClerx** [comment]
@nickerso doesn't mind

@agarny @kerimoyle and @MichaelClerx do

**Comment by MichaelClerx** [comment]
Internal links are already a different colour than the external links, so having it in italics as well seems a bit redundant?
Also to me italics suggests `<em>emphasis</em>`

**Comment by MichaelClerx** [comment]
Outvoted!

**Comment by agarny** [comment]
> Outvoted!

😕

**Comment by MichaelClerx** [comment]
Or not! I forgot that 2 < 3. It's early

**Comment by MichaelClerx** [comment]
This should be done if possible, but as a "nice-to-have"

**Comment by MichaelClerx** [comment]
These links are not even clickable, so the italics indicates a feature that isn't there!
Definitely want to get rid of it

**Comment by MichaelClerx** [comment]
https://groups.google.com/forum/#!topic/sphinx-users/uVd30070evA

**Comment by kerimoyle** [comment]
The links are not clickable?! They should be!?

**Comment by MichaelClerx** [comment]
External links are clickable, and links to (sub*)sections are.
But links to specific lines (e.g. the links to the number definitions) are not.

**Comment by MichaelClerx** [comment]
I'm fine with that, too. If you print it out it doesn't help if we have [this](http://example.com) type of link in the text. So only links like "see [1.2.3 Examples](http://example.com) should have special formatting

**Comment by MichaelClerx** [comment]
I guess latex doesn't allow for hyperlinks to arbitrary paragraphs? Either that or the authors of the spinx translation thought this was a good idea :man_shrugging:
