### ISSUE TITLE
2.12.1 language (top-level of a content MathML tree)

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#246]
> math element MUST be the top-level of a content MathML tree

This should be either:
"math element MUST be the top level of a content MathML tree" (top is the adjective)
OR
"math element MUST be the top-level content of a MathML tree" (top-level is the adjective)

**Comment by agarny** [comment]
"math element MUST be the top level of a content MathML tree" for me.

**Comment by MichaelClerx** [comment]
"content MathML" is a thing, as opposed to "presentation MathML", which is a different thing

**Comment by MichaelClerx** [comment]
(math element) must be the top-level of a (content MathML tree)

**Comment by MichaelClerx** [comment]
I'd suggest replacing with

> math element MUST be the top-level element of a content MathML tree

**Comment by MichaelClerx** [comment]
Or the original "top level" suggestion is fine too

**Comment by MichaelClerx** [comment]
It should be "Content MathML" though, with a capital C
