### ISSUE TITLE
2.15.4 language (`component`s)

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#247]
![image](https://user-images.githubusercontent.com/46887220/79430420-0389f080-801d-11ea-9747-59c5270efa48.png)

Avoid using plurals after the code formatting, rather:

 4. A :ref:`CellML infoset<specA_cellml_infoset>` MUST NOT contain more than one :code:`connection` element with a given pair of :code:`component` elements referenced by the :code:`component_1` and :code:`component_2` attribute values, in any order.

**Comment by MichaelClerx** [comment]
Hold on hold on hold on
It's probably not the `component` element we want to say is being referenced. See #207 again

**Comment by MichaelClerx** [comment]
You reference a "component", not a "`component`"

**Comment by kerimoyle** [comment]
ok, that works too :)
