### ISSUE TITLE
3.2.2.1 end of sentence doesn't make sense?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#250]
![image](https://user-images.githubusercontent.com/46887220/79432342-c70bc400-801f-11ea-8b11-8bdbec263788.png)

"refer to the corresponding built-in units from the table"? or "of the same name from the table"? or something ...

**Comment by MichaelClerx** [comment]
"row". It's missing the word "row"

> from the same row of the table.

**Comment by MichaelClerx** [comment]
or corresponding row or something if you prefer
