### ISSUE TITLE
3.3.1.4: doesn't make sense? (unit product wording)

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#252]
![image](https://user-images.githubusercontent.com/46887220/79432841-7d6fa900-8020-11ea-817b-ea4d1badeff9.png)

The bit in bold confuses me - should delete the bolded **units**? or something else?

The relationship between the product, 𝑃, of numerical values given in each and every child unit element **units**, to a numerical value, 𝑥, with units given by the encompassing units element, SHALL be ...

**Comment by MichaelClerx** [comment]
I think it means the "units" attribute of the "unit element"?
