### ISSUE TITLE
3.3.2 and 3.3.3 use 1) and a)

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#253]
![image](https://user-images.githubusercontent.com/46887220/79433125-dc352280-8020-11ea-9d3f-523a271a164a.png)

In one we use 1) and 2); in the next we use a) and b) ?

**Comment by MichaelClerx** [comment]
I don't recall further 1) or a) points in the spec. Should this really be an indented list of items?

> ... SHALL consist of:
>   1. The units defined...; and
>   2. Built-in ... model.

?
