### ISSUE TITLE
3.3.3.3.3 name element?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#254]
![image](https://user-images.githubusercontent.com/46887220/79433567-62516900-8021-11ea-8ccc-df6b1a63a813.png)

should this be name attribute?? not name element?

**Comment by kerimoyle** [comment]
![image](https://user-images.githubusercontent.com/46887220/79433710-94fb6180-8021-11ea-8945-e136bad32e38.png)

Also in 3.3.3.3.4 ?

**Comment by MichaelClerx** [comment]
wrong screenshots?

**Comment by kerimoyle** [comment]
You are so right. One moment, caller ...

**Comment by kerimoyle** [comment]
![image](https://user-images.githubusercontent.com/46887220/79434032-ef94bd80-8021-11ea-8991-387a9b5ab7ea.png)


![image](https://user-images.githubusercontent.com/46887220/79433999-e7d51900-8021-11ea-8d89-fbfc1019e4e5.png)

**Comment by MichaelClerx** [comment]
Ugh. I guess they mean "element" as in an element of a tuple

**Comment by MichaelClerx** [comment]
Where by "they" I mean "we", I guess

**Comment by MichaelClerx** [comment]
The definition is:

> The “unit reduction” is a conceptual property of units elements. It consists of a set of tuples where each tuple is composed of a) a unit name and b) a real-valued exponent. Tuples SHALL be determined as follows:

Since that just calls it "name" and "exponent", I'd stick with that, and remove the "element" in 3 and 4 and anywhere else it occurs
