### ISSUE TITLE
3.4.1 "valid" CellML identifier?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#255]
![image](https://user-images.githubusercontent.com/46887220/79434325-52865480-8022-11ea-9087-7b21577d9b73.png)

Should we add "valid" to point 3.4.1?

**Comment by kerimoyle** [comment]
(and elsewhere that defines references?)

**Comment by MichaelClerx** [comment]
No. There's no such thing as an invalid CellML identifier.

(For unit/component/variable refs it's not quite as clear, so have left it in there)

**Comment by MichaelClerx** [comment]
We don't say "x SHALL be a valid integer string" etc. either

**Comment by MichaelClerx** [comment]
I think that's the main thing. "CellML identifier" is a data type
