### ISSUE TITLE
3.4.2.1: weirdness ... 

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#256]
![image](https://user-images.githubusercontent.com/46887220/79434578-b01aa100-8022-11ea-8bc7-165aec00691a.png)

shall refer to the **units** specified by that **element**??

**Comment by kerimoyle** [comment]
Also, newlines between sentences here as elsewhere?
![image](https://user-images.githubusercontent.com/46887220/79434746-ece69800-8022-11ea-94a2-951384fdff16.png)

(btw - I've fixed the broken reference)

**Comment by MichaelClerx** [comment]
There's a typo there, should be the "component identifie**d**"

**Comment by MichaelClerx** [comment]
> shall refer to the units specified by that element??

should be "the component specified by that element"

**Comment by MichaelClerx** [comment]
> Also, newlines between sentences here as elsewhere?
> ![image](https://user-images.githubusercontent.com/46887220/79434746-ece69800-8022-11ea-94a2-951384fdff16.png)
> 
> (btw - I've fixed the broken reference)

Not entirely sure! My understanding was that the newlines were in between MUST/SHALL statements that were pretty much separate rules. For this section the second sentence clarifies the first, so it can't be a stand-alone thing.
