### ISSUE TITLE
3.5 numbering/indenting

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#257]
![image](https://user-images.githubusercontent.com/46887220/79434865-14d5fb80-8023-11ea-8c67-58bbb604b6cc.png)

Should point 3.5.3 should be point 3.5.2.1?

"valid CellML identifier"?

**Comment by MichaelClerx** [comment]
> Should point 3.5.3 should be point 3.5.2.1?

Yes

> "valid CellML identifier"?

No
