### ISSUE TITLE
3.6 stuff

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#259]
3.6.2: is a CellML model really a document?
3.6.3: "where the initial_value attribute is a **real number string** ..."  since we've just said in (1) that it has to be one?

![image](https://user-images.githubusercontent.com/46887220/79435558-ee649000-8023-11ea-968c-f21ba8e0f0af.png)

**Comment by MichaelClerx** [comment]
> 3.6.2: is a CellML model really a document?

I think that "document" should go

3.6.3: "where the initial_value attribute is a real number string ..." since we've just said in (1) that it has to be one?

Sure!
