### ISSUE TITLE
Numbering in specification?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#26]
Now that we don't need `when` elements, chapter 13 has disappeared.  Are we intending to keep the same section numbers as in earlier specs, or will they be updated to be contiguous?  
- `math` moves from 14 to 13?  or
- we go from 12 to 14?

What think y'all @nickerso @MichaelClerx @agarny @hsorby ?

**Comment by agarny** [comment]
This is still work in progress, so I would renumber.

**Comment by nickerso** [comment]
as above, agree that we should renumber. The final 2.0 spec should be self-consistent, but no need to match 1.x spec numbering.

**Comment by kerimoyle** [comment]
Thanks all, I've tweaked the spec.
