### ISSUE TITLE
3.9.1: quotes around new conceptual terms in chapter 3

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#260]
- The second sentence is a fragment?
- We only use the term "encapsulation digraph" later, not "conceptual encapsulation digraph"? maybe move the quotes?

![image](https://user-images.githubusercontent.com/46887220/79436176-a3974800-8024-11ea-8b15-99f38fbba729.png)

**Comment by MichaelClerx** [comment]
No it's not?

**Comment by MichaelClerx** [comment]
Yeah better without quotes I think

**Comment by kerimoyle** [comment]
it should be part of the first sentence with a "; therefore" or rewritten "The encapsulation digraph will therefore not ..." ?

**Comment by kerimoyle** [comment]
![image](https://user-images.githubusercontent.com/46887220/79436542-202a2680-8025-11ea-9117-6b7bcbe09168.png)

Should put quotes around "encapsulated set", "encapsulation parent", "sibling set", and "hidden set" as we reference those terms elsewhere?

**Comment by MichaelClerx** [comment]
Yeah ok. So `conceptual "encapsulation digraph"` then, and quotes around these terms when they first appear?

**Comment by kerimoyle** [comment]
yep :)

**Comment by kerimoyle** [comment]
Same deal on the next section?  " conceptual "variable equivalence network" "?
![image](https://user-images.githubusercontent.com/46887220/79436902-93cc3380-8025-11ea-9514-75c0729571c9.png)

**Comment by MichaelClerx** [comment]
Maybe a separate issue for that "therefore" sentence/fragment? I don't think it should be there at all.

It (the thing we're about to define) is a digraph, therefore it doesn't have loops? That's not a thing is it?

**Comment by MichaelClerx** [comment]
I mean, look at wiki's example https://en.wikipedia.org/wiki/Directed_graph
