### ISSUE TITLE
3.10.6-8 applicable and available interfaces?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#262]
Do applicable and available interfaces mean the same thing? if not, should we define the difference? If so, should we pick one and stick to it?
(ignore numbering, fixed elsewhere)

![image](https://user-images.githubusercontent.com/46887220/79437452-5025f980-8026-11ea-8e6b-5a034e1c8b39.png)

**Comment by MichaelClerx** [comment]
I think it's fine the way it is!

`<variable ... interface="public_and_private">` means that this variable has two available interfaces, to be used in connections

the encapsulation structure says which interface is applicable

a connection can only be made if the applicable interface is available

**Comment by MichaelClerx** [comment]
There is a tiny bit of inexact usage going on there, which I'll fix
