### ISSUE TITLE
3.10.9: map_variables wording "equivalent" attribute values --> "identical" 

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#264]
![image](https://user-images.githubusercontent.com/46887220/79437823-d0e4f580-8026-11ea-9a6a-9d93c7db5b4a.png)

Last word is throwing me a little ... ? Surely both the name and exponent value must be identical, there are no equivalences or alternatives here?

**Comment by MichaelClerx** [comment]
Yeah change to identical please
