### ISSUE TITLE
3.11.5 reset value/variable

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#265]
![image](https://user-images.githubusercontent.com/46887220/79438099-33d68c80-8027-11ea-846b-81ee0b3ee682.png)

We define in (1) what a "reset variable" is ... can we use it in (5)? 
"When a reset occurs, the ~variable referenced by the reset element’s :code:`variable` attribute~ **reset variable** SHALL be set to the result of evaluating the MathML expression encoded in the :code:`reset_value`.

**Comment by MichaelClerx** [comment]
Yes please
