### ISSUE TITLE
Are multiple MathML blocks allowed within one component?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#27]
At the moment the spec permits it, but is this really true?

**10.1.2**
A component element MAY contain one or more specific information item children, each of which MUST be of one of the following types:

1. A variable element; or
2. A reset element; or
3. A math element.

**15.1.2**
1. A  math element MUST be the top-level of a content MathML tree, as described in MathML 2.0.
2. Each element information item child of a  math element MUST have an element-type name that is listed in the Supported MathML Elements table.
3. Every variable name given using the MathML ci element MUST be a variable reference to a variable within the component element that the math element is contained.
4. Any MathML cn elements MUST each have an attribute information item in the CellML namespace, with a local name equal to units. The value of this attribute information item MUST be a valid units reference. 
5. The cn element MUST be one of the following types: real or e-notation.
6. The cn element MUST be of base 10.

**Comment by MichaelClerx** [comment]
Absolutely!

There's no difference between

```
<math>
  <apply>
    x = 1
  </apply>
  <apply>
    y = 2
  </apply>
</math>
```

and


```
<math>
  <apply>
    x = 1
  </apply>
</math>
<math>
  <apply>
    y = 2
  </apply>
</math>
```

**Comment by MichaelClerx** [comment]
Don't know _why_ you would do that :D

**Comment by kerimoyle** [comment]
Thanks Michael :)
