### ISSUE TITLE
Remove unneeded support for hoverxref

### ISSUE THREAD

**Issue by agarny** [cellml/cellml-specification#276]
Not only we don't make use of it, but it also breaks our build.

**Comment by MichaelClerx** [comment]
Is it not the thing that makes those tooltips appear?

https://pypi.org/project/sphinx-hoverxref/

**Comment by kerimoyle** [comment]
This is what makes the tooltips appear :) And it only breaks our build really recently ... so it's our fault, no theirs!

**Comment by agarny** [comment]
Closing as this should be fixed, not removed. See PR #277.
