### ISSUE TITLE
2.2.1: href font?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#278]
![image](https://user-images.githubusercontent.com/46887220/79510781-21456d00-8092-11ea-90cf-525db1caa645.png)

Should this circled href not be in codey font?

**Comment by MichaelClerx** [comment]
The linked page also uses `href`, so it's fine?

**Comment by agarny** [comment]
I am fine with it as it is.

**Comment by kerimoyle** [comment]
Okeydokes.
