### ISSUE TITLE
Turn off PDF building on read the docs

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#279]
@kerimoyle says:

> Having said that, because our PDF will be built somewhere else, we should turn off online PDF building from the readthedocs site, and simply serve the "real" PDF via our site. If people want to download the repo and build their own, then that's on them ...

**Comment by MichaelClerx** [comment]
Not required for April 17th release though

**Comment by kerimoyle** [comment]
Done :)
