### ISSUE TITLE
Import of twins permitted?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#28]
> Every import units element MUST contain an unprefixed units_ref attribute. The value of the units_ref attribute MUST be a valid CellML identifier. The value of the units_ref attribute MUST match the value of the name attribute on a units or import units element in the imported CellML infoset. **The value of the units_ref attribute MUST NOT match the value of the units_ref attribute on any sibling import units element.**

I just want to check that this last sentence is true?  We're not allowed to import "twins" for units? (it's allowed when importing components).

**Comment by agarny** [comment]
That's indeed how I read it too (i.e. we are not allowed to import "twins" for units). I must confess that I find that a bit surprising since we can define twin units (e.g. `centimeter` and `cm`)...?

**Comment by kerimoyle** [comment]
Yeah, exactly.  I would have thought you were allowed to import whatever you wanted, how ever many times you wanted, as long as the basic rules around naming were met.  We don't even forbid cyclical imports ... 
Anyone else have ideas? @hsorby @nickerso @MichaelClerx ?

**Comment by MichaelClerx** [comment]
I've never used imports, I'm afraid! Not an expert on that part of the spec :-)

**Comment by hsorby** [comment]
I cannot see the reasoning behind it. My take away is that it is trying to stop duplication of units.  The duplication of components is a slightly different matter so you couldn't apply the same logic to importing units and components.

**Comment by agarny** [comment]
Duplication of units? We can already duplicate units without resorting to imports, e.g.

```
<units name="millisecond">
    <unit prefix="milli" units="second"/>
</units>
<units name="ms">
    <unit prefix="milli" units="second"/>
</units>
```

... or am I missing something?

**Comment by kerimoyle** [comment]
The import->resolve process instantiates units, which means that users could want to import several copies of something complicated, then alter them, exactly as they can alter imported components.  But even if we can't think of a use case which we deem to be sufficiently valid at the moment, I don't understand why the spec should forbid this?  We allow valid-but-dumb models to be created elsewhere?

**Comment by hsorby** [comment]
Sure we can duplicate units I'm just saying that my guess is that the intent here is to try and help out with avoiding valid-but-dumb model creation.

**Comment by hsorby** [comment]
I think the last sentence should be removed I can't see how it could cause an invalid model.

**Comment by kerimoyle** [comment]
> I think the last sentence should be removed I can't see how it could cause an invalid model.

Agreed.

**Comment by MichaelClerx** [comment]
Agreed!

**Comment by kerimoyle** [comment]
It's gone :) Thanks all.
