### ISSUE TITLE
Do we need numbered links for all external references?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#280]
We have several places where we have embedded the website in our text, and it appears in the reference section too.  Should those external sites have numbered references throughout the text so that the paper reader can find them?

**Comment by MichaelClerx** [comment]
How do you mean, "embedded the website in our text" ?

**Comment by kerimoyle** [comment]
![image](https://user-images.githubusercontent.com/46887220/79511490-80f04800-8093-11ea-8507-2cb83292c6d5.png)

Where we've written it as if it will be read online only, so made a clickable link to the reference itself.  Maybe we should be pointing those links to Chapter 4?

**Comment by MichaelClerx** [comment]
I see your point!

Not 100% sure though, external links like these are clickable from the PDF, at least

**Comment by kerimoyle** [comment]
Yep, but printed versions are suddenly without the most important refs?

**Comment by MichaelClerx** [comment]
Well as you say, they're at the end of the spec. But even that's for completeness mostly, no? Most people won't want to manually type the URL into a browser?

**Comment by MichaelClerx** [comment]
If you can do it without changing the flow too much I see no harm :-)

**Comment by hsorby** [comment]
Can we not add superscripts to the link for the reference section here for PDF builder?

**Comment by MichaelClerx** [comment]
How would you go about that? I'd probably prefer a textual fix (e.g. "see chapter 4")

**Comment by hsorby** [comment]
I don't think we need numbered references I would put it down as a nice to have.

**Comment by kerimoyle** [comment]
Can you see what's there and change as needed?  I don't know how to do any of it with latex for the PDF ...?
