### ISSUE TITLE
Single HTML version only shows one level of sections

### ISSUE THREAD

**Issue by agarny** [cellml/cellml-specification#286]
The table of contents for the single HTML version of the spec only shows one level of sections (i.e. `1. Definitions`, but not `1.1. Terminology` for example) while the multi-page HTML version shows two leves of sections, which I find very useful when wanting to quickly access a particular subsection.

**Comment by MichaelClerx** [comment]
Playing around with this now, there's some almost invisible + and - signs to the left of them, that let you expand a longer list

**Comment by agarny** [comment]
Ok, now that @hsorby has updated his branch (see PR #166), everything is fine and this issue is not relevant anymore. I wish the +/- was visible at all times, not only when hovering the the section, but... ok, let's not be too picky!

**Comment by hsorby** [comment]
That will just be some css that could be modified if desired.

**Comment by kerimoyle** [comment]
Ah ... I noticed that now we're showing all levels in section 1 (only) of the main HTML ... is this where that change came from? do we want to change it back?

![image](https://user-images.githubusercontent.com/46887220/79519761-df73f100-80a8-11ea-819c-7ddd2aed0492.png)

**Comment by MichaelClerx** [comment]
Where's that you're looking?

**Comment by MichaelClerx** [comment]
That's not what my `make singlehtml` output looks like

**Comment by kerimoyle** [comment]
It's not the single page one, it's the main html one:
https://cellml-specification-dev.readthedocs.io/en/update_to_cellml2/reference/formal_sectionA.html

**Comment by MichaelClerx** [comment]
Well if it's an issue maybe make a new issue for it. Probably doesn't affect the PDF though
