### ISSUE TITLE
1.1 Terminology 

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#288]
~1. The ordering of terminology is broken by "digit":~

![image](https://user-images.githubusercontent.com/46887220/79519120-0f21f980-80a7-11ea-94dc-b14b8e646363.png)

2. Should we have one for "Unicode" ?

~3. Should these be alphabetical or order-of-use?~

**Comment by kerimoyle** [comment]
Scratch 1, 3, none of them are alphabetical anyway!  Still, do we need to define unicode?

**Comment by MichaelClerx** [comment]
I don't think we need to _define_ it. We don't do that for XML or MathML either (although we state the MathML namespace in the definitions). But we could add a reference to the standard I guess?

**Comment by kerimoyle** [comment]
We have a link to Unicode in the text of one of them (since we had a Unicode reference, it needed to be pointed to ...) it just seemed odd while we're defining Basic Latin and all these things not to also have it defined.  Maybe the reference at first use is enough? (note to self: add refs to those hardcoded links)

![image](https://user-images.githubusercontent.com/46887220/79521148-8d34cf00-80ac-11ea-8521-8981c37ea2ea.png)

**Comment by MichaelClerx** [comment]
Happy with a ref at first use yes

**Comment by MichaelClerx** [comment]
I think this is just a list of terminology, words we use a lot, and where we want to know that people have the exact meaning right. So not definitions. And no need to include things like "Unicode" where we mean nothing more specific than "pretty much any version of Unicode ever"

**Comment by MichaelClerx** [comment]
Happy to close?
