### ISSUE TITLE
Reference and namespace are 5 years apart?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#289]
The reference for the MathML language is here:
'mathml2':         ('http://www.w3.org/TR/2003/REC-MathML2-20031021', ''),
'mathml2_display': ('http://www.w3.org/TR/2003/REC-MathML2-20031021', None),

And for the namespace is here:
'mathml2namespace': ('http://www.w3.org/1998/Math/MathML', None),

... is that ok?

**Comment by MichaelClerx** [comment]
Yup!

https://www.w3.org/TR/2003/REC-MathML2-20031021/chapter7.html#interf.namespace

The 2003 doc says the 1998 namespace is the correct one

**Comment by kerimoyle** [comment]
Sweet.  I like these kinds of issues :)
