### ISSUE TITLE
Should namespace be given as a link or as a literal string?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#292]
In Section 1.1:

![image](https://user-images.githubusercontent.com/46887220/79521204-b0f81500-80ac-11ea-9cd1-51dbc0b9b77c.png)

In section 2.2: 
![image](https://user-images.githubusercontent.com/46887220/79521257-cd944d00-80ac-11ea-871e-3d0c2fe2cb59.png)

**Comment by MichaelClerx** [comment]
I prefer the way it is.

Xlink is used only once, and the definition is given in the section that uses it
MathML and CellML namespaces are used repeatedly, so get a defined term that we can easily reference to

**Comment by MichaelClerx** [comment]
See also #288 . Section 1.1 just makes sure we're clear on some terminology used throughout the spec.

**Comment by MichaelClerx** [comment]
Happy to close?

**Comment by kerimoyle** [comment]
Yeah, I guess.
