### ISSUE TITLE
Why is the normative prologue being built at the homepage of the informative HTML?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#296]
Why is the multi-page HTML build now using the normative landing page??

![image](https://user-images.githubusercontent.com/46887220/79526404-50bba000-80b9-11ea-975a-ba87f2d5adf7.png)

**Comment by agarny** [comment]
I must be missing something: what is wrong with that? What would you expect instead?

**Comment by MichaelClerx** [comment]
Is that a result of #284 ?

**Comment by kerimoyle** [comment]
**This** HTML should be the **informative** spec ...?
I'm expecting three versions:
- PDF normative only
- HTML single-page normative only
- this, HTML, informative ?

**Comment by kerimoyle** [comment]
Yeah, I'm guessing so ...

**Comment by agarny** [comment]
If anything, it should be "normative+informative"...?

**Comment by hsorby** [comment]
> Is that a result of #284 ?

Most definitely.

To change the build type you have to set the environment variable to get the combined document otherwise whatever you build will be the normative spec.

**Comment by kerimoyle** [comment]
Can we do this on different branches then? ie: get this normative stuff merged into master, then switch the readthedocs site other branch to be informative too?

**Comment by MichaelClerx** [comment]
You probably won't want that, you'd have to keep updating the informative branch but working on the normative branch?
Is it possible to set environment variables for readthedocs?

**Comment by MichaelClerx** [comment]
@nickerso just went and fixed this
