### ISSUE TITLE
test_value and reset_value to have single MathML block? or equation?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#30]
Currently the wording is a little unclear:

"A test_value element MUST contain exactly one math element child."  See [here](https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/reference/specB10.html)

"A reset_value element MUST contain exactly one math element child." See [here](https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/reference/specB11.html)

Does this mean a single MathML _block_, which could contain more than one _statement_, culminating in the definition of the `test_variable` and `variable` ?  ie:
```
a = 5 + 3
b = a - 4 
```

Or a single MathML _block_ with a single _statement_ defining the `variable` and `test_variable` values only?
```
b = 5 + 3 - 4
```

**Comment by agarny** [comment]
Starting from your example, if `test_variable`/`reset_variable` is `b` then I would expect `test_value`/`reset_value` to be simply:

`5+3-4`

**Comment by kerimoyle** [comment]
Does this include the left hand side?  ie:
`5+3-4` or `b=5+3-4` ?
... and if so, do we need to specify which variable is on the left hand side?  ie: `b` must be the same as the `test_variable` for the `test_value` element etc?

**Comment by agarny** [comment]
No, no LHS, only the RHS, hence no need to say anything about `b`, i.e. the LHS, since it's the value of `test_variable`/`reset_variable`.

**Comment by kerimoyle** [comment]
... so no `<eq>` tag either? 

```
<apply><plus/>
     <cn>5</cn>
     <cn>3</cn>
     <cn>-4<cn>
</apply>
```

In either case I think we need to reword these points to explain this ... any suggestions?

**Comment by agarny** [comment]
> ... so no `<eq>` tag either?

No, it's also implied. So, indeed, all you need for `test_value`/`reset_value` is:

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
    <apply>
        <plus/>
        <cn cellml:units="dimensionless">5</cn>
        <cn cellml:units="dimensionless">3</cn>
        <cn cellml:units="dimensionless">-4</cn>
    </apply>
</math>
```

> In either case I think we need to reword these points to explain this ... any suggestions?

Maybe something like "A test_value element MUST contain exactly one math element child which in turn MUST contain exactly one apply element."? Then, in the interpretation section, we would have to explain that the apply element corresponds to the RHS...?

**Comment by kerimoyle** [comment]
... and because the contents of the `<apply>` can contain references to variables, the earlier calculation cascade is done outside the reset rather than inside it?  ie:
in the `component` `<math>` block
`a = 5 + 3`
in the `test_value` block:
`a - 4` ?

Thanks for the wording, I'll add it in.

**Comment by agarny** [comment]
> in the `component` `<math>` block
> `a = 5 + 3`
> in the `test_value` block:
> `a - 4` ?

Yes, this is what I would expect, but as always better to come with full example to make sure that we are indeed talking about the *exact* same thing.

**Comment by kerimoyle** [comment]
> A test_value element MUST contain exactly one math element child which in turn MUST contain exactly one apply element.

This doesn't work - you could want to multiply things or perform more than one operation, so then you'd have multiple `<apply>` blocks.  

"A test_value element MUST contain exactly one math element child. The math element child MUST contain exactly one statement/value (?) and MUST NOT contain an `<eq>` tag."

**Comment by kerimoyle** [comment]
Ah, I read "exactly one" as meaning "one overall" not "one child of type apply".  How about:

A test_value element MUST contain exactly one math element child, which in turn MUST contain exactly one child block, which MUST be an apply element.

**Comment by MichaelClerx** [comment]
Alternatively, just say it MUST contain exactly one math element child, and then in the interpretation say the contents of that math element child must specify a single value. We don't specify that the other math elements must contain equations either

**Comment by nickerso** [comment]
> Alternatively, just say it MUST contain exactly one math element child, and then in the interpretation say the contents of that math element child must specify a single value. We don't specify that the other math elements must contain equations either

I think that is what we currently say right? And I think that is the right way to go as we shouldn't control what people put in the math: `apply` won't work as it could also be a `piecewise`, or just a `cn` or `ci`.

**Comment by MichaelClerx** [comment]
> that it evaluates to a single real number

that sounds good to me

**Comment by kerimoyle** [comment]
Is everyone happy with the latest? @MichaelClerx @agarny @nickerso @hsorby https://cellml-specification.readthedocs.io/en/cellml-2-drafting/reference/formal_and_informative/specB10.html

"A test_value element MUST contain exactly one math element child."

There are examples in the informative spec underneath it.

**Comment by agarny** [comment]
Sounds good to me.
