### ISSUE TITLE
First lines of informative spec state it's the normative spec?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#300]
> This document is the normative version of the CellML Specification, defining the CellML syntax and the rules by which it should be used. It is intended primarily for the developers of software tools which directly consume CellML syntax. Users of CellML models may expand the “See more” blocks throughout this document to access the informative version and see examples. Software-specific information is also available under their respective names or icons throughout the text.

**Comment by kerimoyle** [comment]
I guess it should say that it's both? Or ...?

**Comment by MichaelClerx** [comment]
I think it should say it's the informative spec.

Normative + Informative bits = Informative spec?
