### ISSUE TITLE
Missing rule: Import units name can't be that of built-in

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#305]
An `import units` name shouldn't be equal to a built-in unit

Seems we're missing this rule in 2.3

**Comment by agarny** [comment]
I guess you meant `import units`, but that aside: damn, you are right!

**Comment by MichaelClerx** [comment]
> I guess you meant `import units`, but that aside: damn, you are right!

Thanks, updated my comment :-)

**Comment by kerimoyle** [comment]
Import component? Ah :) You got it.
