### ISSUE TITLE
Variable mapping/connection vs variable imports?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#306]
I finally figured out why I was finding it so difficult to debug connected variables in an example that talked about imported components: it's because we're using two different mechanisms to accomplish pretty much the same thing. 

When we import a component, the naming and definition are done in a single step, in a single place:
```
<import href="somewhere.cellml">
   <component_ref component="import_me" name="you_imported_me" />
</import>
```
When we set variables equivalent to one another, we're kind of doing the same thing as importing: we're allowing an outsider to operate locally, but we do it in two different places:
```
<component name="local_stuff">
     <variable name="i_am_really_an_outsider">
</component>

... somewhere totally different in the model ...

<connection component_1="local_stuff" ... >
   <map_variables variable_1="i_am_really_an_outsider" variable_2= ... />
</connection>
```

Is there a rationale behind not using an imported variable within a component to define connections?  The `import` tags could be dropped easily enough.
```
<component name="local_stuff">
     <import>
          <variable name="i_am_really_an_outsider" variable_ref="my_local_name" component_ref="where_i_really_live" />
      </import>
</component>
```

**Comment by MichaelClerx** [comment]
I think that would fix the connections, and stop components being reusable?

**Comment by kerimoyle** [comment]
It's not importing from anywhere beyond where connections are currently permitted?  ie: no href or external stuff, just a change of syntax/thinking around the mechanics we've already got?

**Comment by MichaelClerx** [comment]
It's just that now `local_stuff` has a link to `where_i_really_live` hardcoded, so you can no longer take it out and reuse it in a model, connected to e.g. `where_i_really_live_improved`

**Comment by kerimoyle** [comment]
Hmm, ok, I guess that makes sens.  So even though the link defined above would still break in both cases (if you imported any of the components around, their connections could/would break), in the current syntax you have access to it so can redefine the connection again.  But we don't allow that kind of redefinition in importing components or units, because we assume that if you want to import them in the first place, they're probably already good?

**Comment by MichaelClerx** [comment]
Pretty much, yeah!
So units you just import and re-use as they are, but for components we want to be able to reconnect them.

So if my `<model name="car">` contains a `<component name="engine">`, I can connect the engine to my car's wheels, but you can still import the engine from my car, re-use it in your car, and connect it to _your_ wheels instead.

**Comment by kerimoyle** [comment]
Got it, thanks :)
