### ISSUE TITLE
Imported components can occur in two encapsulations

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#307]
> 2.14.1 The value of the component attribute MUST NOT be identical to the value of the component attribute on any other component_ref element in the CellML infoset.

I _think _ this is OK, because it says "in the CellML infoset".

So an imported component can have children of be in some kind of hierarchy in the importing model, but still exist in a different hierarchy in its own model, without violating this rule?

**Comment by kerimoyle** [comment]
> So an imported component can have children of be in some kind of hierarchy in the importing model, but still exist in a different hierarchy in its own model, without violating this rule?

Yes.  But those children in the importing model would need to be imported explicitly in order to be "seen" by the importing model, so that they could then be encapsulated differently.  The implicitly imported children would not be "seen" by the importing model, so their structure can't change.

**Comment by MichaelClerx** [comment]
Right!

But it wouldn't violate the rule "a component can only appear once in the encapsulation", because we've formulated that as _per infoset_ ?

**Comment by kerimoyle** [comment]
No, because importing twins is permitted -> you can import a component as many times as you like, because each import is a fresh new copy of that component, not the component itself.  The only thing to watch out for is a name conflict, which wouldn't happen in this case because the implicit import is hidden from the importing model.

**Comment by hsorby** [comment]
We think can close this issue as answered.
