### ISSUE TITLE
Wording of attribute requirements

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#31]
Currently we're writing e.g. 

> Every `model` element MUST contain an unprefixed `name` attribute

should we change that to

> Every `model` element MUST contain an non-namespaced `name` attribute

?

- "prefixed" refers to XML syntax, which we're usually not doing in the spec
- You can define unprefixed attributes to be in the parent namespace in an XML schema (See [attributeFormDefault](https://www.intertech.com/Blog/xml-schema-elementformdefault-and-attributeformdefault/_))

Alternatively just

> Every `model` element MUST contain a `name` attribute

And then change 2.4.1 to only be about elements, and add a 2.4.2 saying attributes by default are not in a namespace, unless explicitly stated otherwise?

**Comment by agarny** [comment]
> > Every `model` element MUST contain a `name` attribute
> 
> And then change 2.4.1 to only be about elements, and add a 2.4.2 saying attributes by default are not in a namespace, unless explicitly stated otherwise?

That sounds reasonable to me.

**Comment by kerimoyle** [comment]
Yes, I prefer the last version too.

**Comment by kerimoyle** [comment]
> And then change 2.4.1 to only be about elements, and add a 2.4.2 saying attributes by default are not in a namespace, unless explicitly stated otherwise?

We do this for every element ... would you want to restate that for each of them (ie: for the `model`, for the `component`, for the `units` etc) or is [the earlier statement in 2.4](https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/reference/specA2.html#use-of-namespaces) sufficient?

> Element and attribute information items in a CellML infoset MUST belong to one of the following namespaces, unless explicitly indicated otherwise:
>   - The CellML namespace
>   - The MathML namespace

**Comment by kerimoyle** [comment]
How's this?  See [here](https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/reference/specA2.html#use-of-namespaces)

2.5. Use of namespaces
- Element information items in a CellML infoset MUST belong to one of the following namespaces, unless explicitly indicated otherwise:
     - The CellML namespace
     - The MathML namespace
- Attribute information items in a CellML element MUST NOT be prefixed with a namespace, unless explicitly indicated otherwise.

**Comment by MichaelClerx** [comment]
Is that where the spec lives now?

**Comment by hsorby** [comment]
No, that is where the pretty version that is being worked on lives.
