### ISSUE TITLE
Wording of integer strings

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#32]
> SHALL, when the integer being represented is non-negative, consist of the non-negative integer string representation of the integer.

Bit cyclical?

The same point for reals is made as 

> SHALL, other than the sign indicator and the decimal point separator, consist only of Basic Latin numerals.

which I much prefer

**Comment by agarny** [comment]
Agreed.

**Comment by kerimoyle** [comment]
That's a lot clearer. Consider it done :)

**Comment by kerimoyle** [comment]
How's [this](https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/reference/specA3.html)?

**Comment by MichaelClerx** [comment]
Looks like the current wording doesn't exclude e.g. `1-2`

Maybe something like

Second point: If negative consist of sign + non-neg int string
Third point: If not negative consist of non-neg int string

?

**Comment by hsorby** [comment]
I don't think so, doesn't it say that the sign character is the first character?

**Comment by agarny** [comment]
> How's [this](https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/reference/specA3.html)?

Just in case, I am getting this message when trying to open the above link using Google Chrome:

![Screen Shot 2020-03-09 at 10 20 23 AM](https://user-images.githubusercontent.com/602265/76204161-c2b5e500-61ef-11ea-94ca-eb62e86ed33c.png)

**Comment by kerimoyle** [comment]
Thanks @agarny, that's just because I was debugging something else
unrelated and turned alerts on recently.

**Comment by kerimoyle** [comment]
Closing as finished.
