### ISSUE TITLE
Emend Table 2.1 in section 2.12: remove asterisk

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#337]
![image](https://user-images.githubusercontent.com/46887220/90563369-d3837180-e1f7-11ea-8c1e-04752b156b4b.png)

We need to remove the asterisk from the `degree` element in the normative spec.

**Comment by MichaelClerx** [comment]
Before we merge that in, should we update a version number somewhere to indicate this whole repo is now POST publication spec?

**Comment by hsorby** [comment]
This issue has been resolved by removing the statement about the `degree` element which was incorrect.
