### ISSUE TITLE
Semantic equivalence rewording

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#34]
Can we change "zero or more" to be "any or none"?  And can we reword the final sentence (doesn't quite make sense at the moment?) or bracket the third point?  See [here](https://cellml-specification-dev.readthedocs.io/en/latest/reference/specA2.html#semantically-equivalent-cellml-infosets)

> 2.3. Semantically equivalent CellML infosets
> - Two CellML infosets SHALL be deemed semantically equivalent if one can be transformed into the other by making **zero or more** of the following changes:
> 
>    - Adding, removing, and/or modifying comment information items.
> 
>    - Changing (inserting, removing, and/or modifying) one or more namespace information items, and/or modifying the prefix of one or more information items, without changing the namespace that any information item is in.
> 
>    - The following paragraph applies only to character information items which are the direct child of an element information item in a CellML namespace, or in the MathML namespace.
> 
>      Inserting or removing character information items that consist entirely of whitespace characters, changing the number of whitespace characters in such an information item, or changing the number of whitespace characters at the beginning or end of any character information item.

**Comment by MichaelClerx** [comment]
What's wrong with the 3d point?

**Comment by kerimoyle** [comment]
It's a sentence fragment.  I think it would be clearer to either reword the whole lot, or put the first bit in brackets so the bullet points follow cleanly:


2.3. Semantically equivalent CellML infosets

Two CellML infosets SHALL be deemed semantically equivalent if one can be transformed into the other by making zero or more of the following changes:

  - Adding, removing, and/or modifying comment information items.

  - Changing (inserting, removing, and/or modifying) one or more namespace information items, and/or modifying the prefix of one or more information items, without changing the namespace that any information item is in.

  - (The following paragraph applies only to character information items which are the direct child of an element information item in a CellML namespace, or in the MathML namespace):
Inserting or removing character information items that consist entirely of whitespace characters, changing the number of whitespace characters in such an information item, or changing the number of whitespace characters at the beginning or end of any character information item.

**Comment by kerimoyle** [comment]
Closed by #94
