### ISSUE TITLE
Real number equation is wrong?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#35]
See [here](https://cellml-specification-dev.readthedocs.io/en/latest/reference/specA3.html)

Currently we have: 

> 3.5. A real number string:
>   1. SHALL be a base 10 representation of a real number `r=s⋅10e`, where `s` is the significand, a real number, and `e` is the exponent, an integer.

I think that the exponent `e` should be (erm) an exponent?  ie: `r=s.10^e` ?

**Comment by MichaelClerx** [comment]
Yeah I think that got lost in the conversion from google doc :D

**Comment by kerimoyle** [comment]
Done :)
