### ISSUE TITLE
Unicode reference

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#36]
We currently include references to unicode symbols via the fileformat.info site (eg: [here](http://www.fileformat.info/info/unicode/char/0041/index.htm)).  This was written in 1993 ... I'm wondering whether we need to define the version we're using (through perhaps the unicode site itself?), and/or update to something this millennium?

**Comment by kerimoyle** [comment]
Ping @MichaelClerx @nickerso @agarny @hsorby

**Comment by hsorby** [comment]
I can't get to the reference for the symbol anywhere on the unicode site whilst the fileformat.info takes me directly to the definition.  I find the fileformat.info location the most helpful but as you say quite out of date.  I was trying to find similar info for version 5 as that is the ISO standard but cannot.

**Comment by hsorby** [comment]
I think that letter hasn't changed since version 1 1993 so it has stayed the same further versions then build upon older versions?

**Comment by kerimoyle** [comment]
Yeah, I'm guessing that none of the characters we care about are likely to change all that much ... though am now wondering whether they're better specified as UTF-8 if that's really [the default for XML](http://www.utf-8.com/)?

**Comment by kerimoyle** [comment]
OK, a bit more digging shows that they the fileformat.info site doesn't update when newer versions are released, it just adds the new characters (eg: if we ever needed a [llama](https://www.fileformat.info/info/unicode/char/1f999/index.htm), we're in luck, it was added in 2018).  So I guess we're fine, I'll close this now.  Thanks @hsorby!

**Comment by hsorby** [comment]
Oh we have to change the spec. we definitely need a llama!

**Comment by kerimoyle** [comment]
My thought too ... sigh ... perhaps it will find its way into a tutorial or two ;)

**Comment by MichaelClerx** [comment]
You can use them in URLs too http://michaelclerx.com/%f0%9f%a5%83/
