### ISSUE TITLE
CellML2.0 namespace link is not found?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#37]
The spec uses this link for the CellML2.0 namespace, but it seem to exist yet.  Is that because that's where this doc will go, or should it point somewhere else?

`https://www.cellml.org/cellml/2.0#`

... and why does it need to finish with a hash when there's no bookmark defined?

**Comment by MichaelClerx** [comment]
Namespaces need to be URIs, but nothing _has_ to exist at that URI. It's fairly common to put something there

The hash is a convention, see e.g. RDF

    http://www.w3.org/1999/02/22-rdf-syntax-ns#

but not MathML

    http://www.w3.org/1998/Math/MathML

the idea is that you can point to an element in the namespace by doing `namespace_uri + element_name`, without having to stick anything in the middle

**Comment by hsorby** [comment]
It is a nice to have the actually definition at that location but it is not actually required that something is there.

**Comment by nickerso** [comment]
yep - not required but we will eventually have them resolvable.
