### ISSUE TITLE
Should we define the "empty namespace"?

### ISSUE THREAD

**Issue by agarny** [cellml/cellml-specification#4]
Originally from [jonc125](https://github.com/jonc125):

This phrase is used more than once, but isn't actually defined by the Namespaces in XML specification.

**Comment by MichaelClerx** [comment]
Decision was: No
Phrase has been removed from the spec

See also: https://groups.google.com/forum/#!topic/cellml-language-spec-writing/toSf5RZkWCc
and: https://groups.google.com/forum/#!msg/cellml-language-spec-writing/wVOfS88Xh6k
