### ISSUE TITLE
Connection element rules

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#41]
Really small issue, but 15.1 has rules for the component_1 attribute, and then 15.2 the same for the component_2 attribute + the restriction that it can't be equal to 15.1. This is a rule for both attributes, so should be a separate point (15.3) I think

**Comment by kerimoyle** [comment]
Done :) See https://cellml-specification-dev.readthedocs.io/en/latest/reference/specB15.html

**Comment by kerimoyle** [comment]
Closing as finished.
