### ISSUE TITLE
Units reference rules numbering

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#43]
> C4.2 A CellML infoset MUST NOT contain a units reference for which no referencing rule can be held to have been followed.
> C4.3 The units referencing rules are:
> C4.3.1 ...

Do we need a new point here? Can "The units referencing rules are:" not just be the last sentence of C4.2?

**Comment by kerimoyle** [comment]
It might be easier to reference if they are separate - otherwise do you send errors to 4.2 (ie, the whole thing) or 4.2.1 or both?

**Comment by kerimoyle** [comment]
Closing as out of date.
