### ISSUE TITLE
Radians and sterradians

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#45]
Currently defined as meter/meter?

https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/reference/specC2_units_reference.html

- First, isn't that an incomplete unit reduction? I'd expect this to be simplified to {}
- Secondly, if we're going to be really strict about them, shouldn't these both be base units?

**Comment by jonc125** [comment]
It's because the radian is defined in SI as the ratio of two lengths, and CellML follows SI for the built-in units (mostly).

**Comment by MichaelClerx** [comment]
But that still wouldn't give us that as a unit reduction, right?

**Comment by MichaelClerx** [comment]
> Where the set of tuples consists of tuples which have the same name element, those tuples SHALL be combined into a single tuple with that name element and an exponent being the sum of the combined tuples’ exponents. If the resulting tuple’s exponent term is zero, the tuple SHALL be removed from the set of tuples. Note that this can result in the set of tuples being empty.

So there's no way to distinguish between the ratio of two lengths and plain old dimensionless in CellML

**Comment by nickerso** [comment]
If you used libCellML to compare radians and dimensionless, then they would be the same. In the past people have expressed the opinion that it is useful to keep these ratio type units as having their actual definition as per SI. Strain is often the other one that is a length ratio that some people use as dimensionless and some use as m/m.

**Comment by MichaelClerx** [comment]
That's good! But we still can't have "metre/metre" as the units reduction of radians, because it's not a units reduction :D

**Comment by jonc125** [comment]
It can still be the definition though, just not in fully reduced form :)

**Comment by MichaelClerx** [comment]
So what we're saying is that, _in CellML_, radian == sterradian == dimensionless.
But then, uniquely, we use the spec to say that they're a kind of dimensionless with an interesting backstory?

**Comment by MichaelClerx** [comment]
For the other derived SI variables we don't give a backstory, e.g. `pascal = N / m^2`. We just give the reduction, as that's the only meaningful thing in CellML, and the only useful thing for reading the spec.

I mean, I don't _want_ radians and sterradians to be new base units as that'd be another feature I need to implement in Myokit and cellmlmanip. But it makes no sense for me to hide this CellML deficiency by saying "radian == dimensionless but it used to not be". Let's just own up to it :D

**Comment by kerimoyle** [comment]
OK ... so what do I write and where?  I can change the radian and steradian line in the table [here](https://cellml-specification.readthedocs.io/en/cellml-2-drafting/reference/formal_and_informative/specC02_units_reference.html)?  Or leave as is?

**Comment by agarny** [comment]
I haven't thought about the potential implications, but I would expect `radian` and `sterradian` to be base units.

**Comment by kerimoyle** [comment]
Base units?? Why??  I don't think the should be at all - they're not one of the seven fundamental physical properties, they're derived, _and_ they're covered by the `dimensionless` base unit.  

Standard/built-in, sure ... but the question is whether their definition in this table is `m/m` or `m^2/m^2` or changed to `dimensionless` to be more consistent with the other minimally specified derived units?

**Comment by kerimoyle** [comment]
> For the other derived SI variables we don't give a backstory, e.g. pascal = N / m^2.

This is maybe because that's then two levels of derivation?  ie - interpreting Newtons first and then into Pascals?

**Comment by agarny** [comment]
> Base units?? Why?? I don't think the should be at all - they're not one of the seven fundamental physical properties, they're derived, _and_ they're covered by the `dimensionless` base unit.

I know, it's just that I wish we could really distinguish between `radian`, `sterradian` and `dimensionless`. If we can't then I don't really see the point in listing `radian` and `sterradian`.

> Standard/built-in, sure ... but the question is whether their definition in this table is `m/m` or `m^2/m^2` or changed to `dimensionless` to be more consistent with the other minimally specified derived units?

If that's the only question we want to address here, then I would probably add a column where we would give the definition of a given unit. This means that for `radian` for example, we would mention `metre/metre` for the definition, but then `dimensionless` for its reduction. As for `pascal`, the definition would `N/m^2`, but its reduction `kg/m/s^2`.

**Comment by kerimoyle** [comment]
> I would probably add a column where we would give the definition of a given unit. 

That's reasonable.  I'll add a "Commonly defined as" column to the table, and make the reductions the most simple reduction possible.

**Comment by MichaelClerx** [comment]
You can't add radians to sterradians, or to volt/volt or anything like that, so I agree they should really be base units _or_ we just admit that they're an alias for dimensionless in CellML

**Comment by kerimoyle** [comment]
> You can't add radians to sterradians, or to volt/volt or anything like that 

Why not?

**Comment by MichaelClerx** [comment]
Because they're different things

**Comment by kerimoyle** [comment]
Not a CellML problem ... ?

**Comment by MichaelClerx** [comment]
I don't understand. We don't say "volt = dimensionless" or anything like that in CellML. We don't have other conceivable dimensionless units i.e. "number of cows". So why do we have this one and then not have it as a base unit? We're actually _stopping_ users from having them as base units with this construct

**Comment by kerimoyle** [comment]
We do say "volt/volt = dimensionless" or "cow/cow = dimensionless" ... I don't see the difference here.  All that the reduction is saying is that on the one occasion that units need to be equivalent (connected variables) that this is how that equivalence will be calculated.  I'm not clear how that's stopping anyone doing anything?

**Comment by MichaelClerx** [comment]
Well that's fine because cow/cow _can_ be added to volt/volt, or dimensionless

**Comment by MichaelClerx** [comment]
But radian != sterradian != dimensionless

**Comment by MichaelClerx** [comment]
I'm probably wrong here but I don't understand why

**Comment by MichaelClerx** [comment]
https://math.stackexchange.com/questions/803955/why-radian-is-dimensionless

**Comment by kerimoyle** [comment]
Here are the options then:

1) Move radians and steradians to be base units.  
     - means that we can no longer have equivalence between any units derived from these (ie: radians/second can no longer be equivalent to metre/(metre*second) ) ... this feels like a bad idea to me.

2) Ditch defining both radians and steradians anywhere:
     - means that people can define them themselves as new units ... but ...
          - if they define them as base units, then the above applies, that they won't be able to be reduced with respect to anything else
          - if they define them as derived units (ie: metre/metre) then they can be used with respect to other things, but this is no different to what we have now, as they reduce to dimensionless in the comparisons ...

3) ...? 

So I'm just confused about where the trouble actually is ...?  If it's a broader philosophical thing then reckon it's out of scope.  If there's a compelling reason that users should be prevented from making an equation/situation in which they equate m/m with dimensionless or radians, then we need to look at how we do all the unit definitions everywhere ...?  I feel like I must be missing the point completely here!

**Comment by MichaelClerx** [comment]
I (and it seems Alan) just thought that they shouldn't be the same as dimensionless, that that was a mistake. But it seems the SI thought that _until_ 1995 and then changed its mind? https://en.wikipedia.org/wiki/SI_derived_unit#Supplementary_units

**Comment by kerimoyle** [comment]
I'm totally fine with them not being the same thing ... I'm just struggling to see how it should affect the spec (especially as, at the moment, we can say volt + cow = train_of_chocolate if we want to ...)

**Comment by MichaelClerx** [comment]
If they weren't you couldn't connect a variable x in radians to a variable x in dimensionless, for example

**Comment by MichaelClerx** [comment]
I think the current resolution would be to keep it as it is but just remove the "meter / meter" thing from the unit reduction column (as it's not a reduction: it can still be reduced to dimensionless)

**Comment by kerimoyle** [comment]
OK, that's fine.  I think adding a final column to correspond with the "equivalents" column in that wikipedia page (we currently have the "base equivalents" column already) might help clear things up?

**Comment by kerimoyle** [comment]
Updated now, see: https://cellml-specification-dev.readthedocs.io/en/i64_ref_vs_reference/reference/formal_only/specC02_units_reference.html#table-built-in-units

**Comment by MichaelClerx** [comment]
Thanks!
The final column is nice, but is it a bit out of scope?

**Comment by kerimoyle** [comment]
Haha, kinda agreed re scope ... but the only reason for having it was so we could have metre/metre next to radians somewhere ... and then adding that column meant needing to fill it for other units too!

**Comment by agarny** [comment]
Agreed too, but I think it's fine. Otherwise, one minor thing: use `⋅` rather than `*` in the unit reduction column.

**Comment by kerimoyle** [comment]
Closed by #87
