### ISSUE TITLE
Unit checking in equations

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#46]
~In CellML 2.0, we've got obligatory unit conversion in connections~
A CellML 2.0 model is invalid if connected variables have incompatible units.

But I think we've scrapped all the rules about units in e.g. log() and exp()? Is a file valid if the units in the equations are wrong?

**Comment by agarny** [comment]
> In CellML 2.0, we've got obligatory unit conversion in connections

FWIW, it is the same in CellML 1.0/1.1.

> But I think we've scrapped all the rules about units in e.g. log() and exp()? Is a file valid if the units in the equations are wrong?

@nickerso to confirm, but I would say that it is indeed valid. It would just not make sense, hence when analysing (and not validating) the model, libCellML should generate a warning (and not an error).

**Comment by MichaelClerx** [comment]
There's definitely places where 1.0/1.1 seems to say it's optional

> CellML processing software is not required to
be capable of converting between units definitions. However, for interoperability, software that does implement this
functionality should achieve the same results as if this method were used, although the exact implementation may differ.

But then also

> For interoperability, CellML processing software should take into account the units definitions referenced by any two variables that are mapped together. If the units references are not equivalent, as defined in Appendix C.2.1, then a conversion may be required. An algorithm for performing this conversion is proposed in Appendix C.3.5.

This never shows up in the rules bits though

**Comment by MichaelClerx** [comment]
We've got this in 2.0 now

> 10.3 Units referenced by a units attribute information item SHALL NOT affect the mathematical interpretation of the CellML model.

**Comment by MichaelClerx** [comment]
Wonder if we should provide some guidance on what unit checking might be sensible? E.g. no log(m) etc?

**Comment by MichaelClerx** [comment]
Still wondering about this a bit:

> For interoperability, CellML processing software should take into account the units definitions referenced by any two variables that are mapped together. If the units references are not equivalent, as defined in Appendix C.2.1, then a conversion may be required. An algorithm for performing this conversion is proposed in Appendix C.3.5.

That says that CellML processing software should do some conversion (or at least that it "may be required"). **Doesn't say that inconvertible units make a model invalid though!**

In CellML 2.0 we say

> For each ​ map_variables​ element present in the CellML model, the variable unit reduction (see ​ Effect of units on variables​ ) of variable ​ A ​ MUST have an identical set of tuples to the variable unit reduction of variable ​ B ​ . Two sets of tuples SHALL be considered identical if all of the tuples from each set are present in the other, or if both sets are empty. Two tuples are considered identical if and only if both the name and exponent value of each tuple are equivalent.

So that has a much clearer rule on validity of CellML docs

**Comment by nickerso** [comment]
yep - I agree with @agarny's comment. Comes back to CellML being the syntax not the model - bad models can be valid CellML. Ideally we provide model debugging tools that help users find obviously bad things like units in math being messed up, but that is not the role of the CellML specification itself.

**Comment by MichaelClerx** [comment]
_except_ for connections, there validating the syntax suddenly involves unit conversion

**Comment by nickerso** [comment]
Yep - within math is up to the model/modeller, connections are a consequence of modularity and therefore needed in the spec to ensure interoperability.

**Comment by kerimoyle** [comment]
I've written something about this in the informative spec <math> section, see the 4th "see more" section here: https://cellml-specification-dev.readthedocs.io/en/latest/reference/specB12.html
I'll add something similar to the Section C: Interpretation chapter section too.

**Comment by kerimoyle** [comment]
Can I close this now @MichaelClerx ?

**Comment by MichaelClerx** [comment]
Yes. Thanks!
