### ISSUE TITLE
Clarify MathML wording

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#52]
See: https://cellml-specification.readthedocs.io/en/cellml-2-drafting/reference/specB12.html

> 3. Every variable name given using the MathML `ci` element MUST be a variable reference to a variable within the component element that the math element is contained.

.. doesn't make sense?  Can we change this to be "Every variable name given using the MathML `ci` element MUST be a variable reference to a variable within the component element **in which** the math element is contained.

> 4. Any MathML `cn` elements MUST each have an attribute in the CellML namespace, with a local name equal to units. The value of this attribute MUST be a valid units reference.

Do we need to say that the units reference need to be in the model?  We don't actually say what a valid units reference is anywhere?  There's also no "Interpretation of units reference" part in Section C: Interpretation.  Do we need one ...?

> 5. The `cn` element MUST be one of the following types: real or e-notation.

Change to "Any MathML `cn` elements MUST ..." to be consistent with above?

> 6. The cn element MUST be of base 10.

Ditto - "Any MathML `cn` elements MUST ..." to be consistent with above?

**Comment by kerimoyle** [comment]
Thoughts on this one? @agarny @nickerso @MichaelClerx @hsorby ?

**Comment by agarny** [comment]
> See: https://cellml-specification.readthedocs.io/en/cellml-2-drafting/reference/specB12.html

FWIW, that page doesn't exist anymore.

> .. doesn't make sense? Can we change this to be "Every variable name given using the MathML `ci` element MUST be a variable reference to a variable within the component element **in which** the math element is contained.

Agreed with changing **that** to **in which**.

> Do we need to say that the units reference need to be in the model? We don't actually say what a valid units reference is anywhere? There's also no "Interpretation of units reference" part in Section C: Interpretation. Do we need one ...?

I would say: yes, n/a, probably. :)

> Change to "Any MathML `cn` elements MUST ..." to be consistent with above?

Agreed with regards to consistency. However, I would rather have something like "A MathML `cn` element MUST..."

**Comment by MichaelClerx** [comment]
>   ... doesn't make sense? Can we change this to be "Every variable name given using the MathML ci element MUST be a variable reference to a variable within the component element in which the math element is contained.

Yes

> Do we need to say that the units reference need to be in the model? We don't actually say what a valid units reference is anywhere? There's also no "Interpretation of units reference" part in Section C: Interpretation. Do we need one ...?

Section 18.2 ?

> Final two

yes!

**Comment by kerimoyle** [comment]
See #92 for changes.  Rendered version here: https://cellml-specification-dev.readthedocs.io/en/i52_mathml_wording/reference/formal_and_informative/specB12.html

**Comment by kerimoyle** [comment]
Closed by #92
