### ISSUE TITLE
C7 Variable reference point 2 still needed?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#53]
From here: https://cellml-specification.readthedocs.io/en/cellml-2-drafting/reference/specC5_variable_reference.html

> C7. Variable reference
> 1. When present in an information item which is a descendant of a component element, a variable reference SHALL be the name of a variable, and SHALL refer to the variable element in that component with a name attribute identical to the variable reference.
> 2. In all other cases, a variable reference SHALL consist of a component reference and a variable name. In this case, the variable reference SHALL be treated as if it was just the variable name present in the component element referenced by the component reference.

Just wondering about 2 - where are these other cases?

**Comment by MichaelClerx** [comment]
:thinking:

**Comment by nickerso** [comment]
Connections. 1 is essentially dealing with variables in math and 2 is dealing with variables in connections. (I'm sure I'm forgetting others but those are the main ones springing to mind right now).

**Comment by kerimoyle** [comment]
Kiiiiiinda ... but it's not clear that the "component reference" is the `component_1` or `component_2` in the `connection` element?  I was expecting something like `<something variable="myComponent:myVariable">` from the wording.  If it's only in connections can we just say that?

**Comment by MichaelClerx** [comment]
@kerimoyle is this one fixed now?

**Comment by kerimoyle** [comment]
Yes :)
