### ISSUE TITLE
IDs and imports

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#55]
Is it OK for us that ids are a document-wide thing, so that a model with imports may have several components that have the same id?

**Comment by agarny** [comment]
Isn't the point of an ID to be unique across a whole document? If so, then we clearly can't have two different components (which are the result of importing a given component twice) with the same ID...? IOW, although there is probably nothing that prevents us from giving an ID to an importable component, it probably doesn't make sense to do that...?

**Comment by MichaelClerx** [comment]
The document isn't the model, that's the thing: a model can be made from several documents.
So you could have 3 valid model documents, each with a component with id "A"
And then have a 4th valid model document that imports all three

**Comment by agarny** [comment]
Yes, that's similar to what I had in mind, i.e. having a model document that defines a component with ID `A` and then have that component imported several times. In principle, there is nothing that prevents you from doing that, but it probably doesn't make much sense...?

As far as I can tell, the spec doesn't say anything about an ID having to be unique across a model document? If so, that means that validation wouldn't complain about it, but when analysing the model we would...?

**Comment by MichaelClerx** [comment]
I think it might still make sense

I think the IDs are only used to attach metadata, and if you do that in an external file you have to refer to the ID as something like `"./document_1.cellml#this_is_the_id"`. So it should be possible to use these IDs sensibly, it just means that we have to be aware of this when parsing?

**Comment by agarny** [comment]
I indeed believe we only use IDs for annotation.

So, I guess it all depends on what your ontological term / composite annotation is going to be exactly. E.g., you might have a component `X` that defines the Hodgkin-Huxley formulation, and then have that component imported several times for different activation/inactivation gate processes.

So, if you have an ID on `X` and some annotation associated with it then the annotation would have to be related to the fact that `X` is the Hodgkin-Huxley formulation and not this or that in/activation gate.

From there, I am wondering whether there is a way to give an ID and therefore annotate an imported component...? @nickerso?

**Comment by nickerso** [comment]
As @MichaelClerx says, the `id` is used as the fragment identifier in combination with the serialised document filename (and potentially path and server information) to make a URI that is used when you want to describe that specific resource in a CellML document (not model).

When importing a component or units, you are defining a new component or units in the current model which is a pointer to the component or units in the source model. This new local component or units can (and should) have its own `id` which allows you, when you have serialised the model to an XML document, to describe that resource differently to the description of the source component or units. A good example could be a component `HH-gate` which is imported as a `m-gate` and a `n-gate`.

If you were to flatten a model with imports, the flattening tool needs to account for `id` conflicts and resolve those as `XML:ID` attributes by definition must be unique across a given document.

So to answer @MichaelClerx's original question is:

> Is it OK for us that ids are a document-wide thing, 

Yes.

> so that a model with imports may have several components that have the same id?

as above, this is incorrect.

**Comment by MichaelClerx** [comment]
So a _flattened_ model couldn't have two components with the same ID, but a non-flattened one could, because it's (document URI, ID) that needs to be unique?

**Comment by agarny** [comment]
> So a _flattened_ model couldn't have two components with the same ID, but a non-flattened one could, because it's (document URI, ID) that needs to be unique?

That's my understanding.

**Comment by nickerso** [comment]
> So a _flattened_ model couldn't have two components with the same ID

correct.

> but a non-flattened one could, because it's (document URI, ID) that needs to be unique?

incorrect. The source component `id` is never present in the importing model. If you want the imported component to have an `id` in the importing model document then you need to give it an `id` in the local model. Not sure if that is making it any clearer :)

**Comment by MichaelClerx** [comment]
OK hold on. I'm thinking of a "model" as an entity that can live in several documents, and components from that model that live in different documents can have the same `id` without problems, as far as I can see.

And you're talking about a "model information item", which is a thing that lives in a single CellML document, by definition?

**Comment by agarny** [comment]
> > but a non-flattened one could, because it's (document URI, ID) that needs to be unique?
> incorrect. The source component `id` is never present in the importing model. If you want the imported component to have an `id` in the importing model document then you need to give it an `id` in the local model. Not sure if that is making it any clearer :)

Could you give an example of an "imported component [having] an `id` in the importing model document"? I am not sure where this could be done. I mean, say that we have:

```
<import xlink:href="source.xml">
    <component component_ref="imported_component" name="local_component"/>
</import>
```

So, would you put the id on the `component` element, i.e. something like:

```
<import xlink:href="source.xml">
    <component cmeta:id="unique_id" component_ref="imported_component" name="local_component"/>
</import>
```

?

**Comment by MichaelClerx** [comment]
I'm wondering now if we should make sure in the spec (and perhaps in implementations e.g. libcellml) that an `id` is a document-level thing? If it's unique _within a document_, that means it needs some concept of a document, which the rest of cellml doesn't have?

**Comment by nickerso** [comment]
yep, `id` is purely a serialisation thing so that external things can reference specific entities in a CellML document. They have no other role beyond that.

**Comment by MichaelClerx** [comment]
@kerimoyle do you think we should add something about this in the informative spec? Something to say that

- ids are a parse-time construct
- ids are unique within a document, but a document containing an id `x` is allowed import a component/unit from another document that also has id `x` (since these things should have disappeared after parsing anyway!)

**Comment by kerimoyle** [comment]
Sure, we can add something - after section 1.2.6?

**Comment by MichaelClerx** [comment]
Yes please!

**Comment by kerimoyle** [comment]
> yep, id is purely a serialisation thing so that external things can reference specific entities in a CellML document. They have no other role beyond that.

@nickerso how do those external things reference specific entities if the ids are duplicated?

**Comment by nickerso** [comment]
Valid `id`s are never duplicated in a document. The XML ID attribute type is used as the fragment identifier in a URI, so examples of usage would be `model.xml#INa-component` or `https://models.physiomeproject.org/workspace/1234/models/model8.cellml#u_0987654321` - which would resolve to an XML element in a CellML document.

**Comment by kerimoyle** [comment]
> Valid ids are never duplicated in a **document**. 

.. but they may be _between_ documents?  Is what I've written in the example correct? See: https://cellml-specification-dev.readthedocs.io/en/i55_ids_and_imports_informative/reference/formal_and_informative/specA2.html

**Comment by MichaelClerx** [comment]
Yup, it's correct! I've added some comments on the PR

**Comment by kerimoyle** [comment]
Sorry @MichaelClerx, I'll close when the pr is merged or I will get lost...

**Comment by MichaelClerx** [comment]
Oh, sorry! I thought it was done :D
