### ISSUE TITLE
Initial value as variable - do we still need it?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#56]
CellML 1.1 introduced having variables as `initial_value` attributes:

> The value of the initial_value attribute may be a real number or a variable. A modeller may wish to store the initial and boundary conditions in a separate file that is imported by the current model.

So now you could do e.g.
```
<model>
  <comp>
    <var x initial_value="y"
    <var y public_interface="in">
    <math>
      dx/dt = ...
```
and then have an imported CellML file that sets `y`, along with all the other initial values

In CellML 2.0 you can do this more easily, as
```
<model>
  <comp>

    <var x interface="public">
    <math>
      dx/dt = ...
```
because with the loss of directionality you can set an initial value anywhere in the connected variable set.

So... do we still need the initial-value-is-a-variable construct? It'd reduce the burden on implementers, and probably simplify resets too

**Comment by agarny** [comment]
Good question! I would definitely be in favour of getting rid of that feature since it would indeed make things easier, e.g. with regards to code generation (I was actually going to check whether we support it and do it, if needed). @nickerso?

**Comment by MichaelClerx** [comment]
@jonc125 do you have thoughts on this?

**Comment by nickerso** [comment]
We don't *need* the initial value as a variable in 2.0, but this is a significant change and will impact model translation where people are following "best practice" and using this feature in CellML 1.1 models to separate the math from the parameters. Coming up with a translation which respects this separation may need more than an XSLT...

**Comment by MichaelClerx** [comment]
Are many people using the feature? I've never once had an problem due to not supporting it

**Comment by agarny** [comment]
> We don't _need_ the initial value as a variable in 2.0, but this is a significant change and will impact model translation where people are following "best practice" and using this feature in CellML 1.1 models to separate the math from the parameters. Coming up with a translation which respects this separation may need more than an XSLT...

So, your concern is about the conversion from CellML 1.1 to CellML 2.0. If so, then I wouldn't consider this as being a valid reason for not dropping the initial value as a variable. As you confirmed, that feature is not needed in CellML 2.0. So, it should be dropped. Simple as that. (That's why we are going from 1.x to 2.x., to allow "big" changes.)

**Comment by nickerso** [comment]
my concern is that changing things that already exist (I use this feature a lot) will break stuff and slow the release of the specification (and open up the discussion on what goes into 2.0 once more). I'm not seeing enough of a reason to hold up the spec to make this change. I can easily see this cascading into a re-evaluation of CellML 2.0 and other items that could/should be removed. I'd be much more comfortable leaving this alone for now and removing in 2.1 or 3.0 if we determine that no one is using this going forward.

**Comment by jonc125** [comment]
> @jonc125 do you have thoughts on this?

I've never supported it, but then all my stuff only supports CellML 1.0 still :)

**Comment by agarny** [comment]
Not what I want, but I can see and understand your concern. What we could do then is to keep that feature in 2.0, but make it official that it's not recommended practice anymore and that it will be officially removed in 3.0 (not 2.1)?

**Comment by MichaelClerx** [comment]
I don't think we should pre-empt the future specs, but we could definitely add a note saying use of this feature is not recommended now.
Not sure that'd go in the normative spec though?

**Comment by agarny** [comment]
That's something that a lot of libraries do, but maybe not specifications indeed.

**Comment by kerimoyle** [comment]
We have plenty of place to put a "by the way" kind of notice that's not in the official spec wording.  But I'm curious - are we not making it harder for people to be "good" modellers by separating out their parameters from their model by forcing them to use a constant to initialise them?  I kinda thought that would be encouraged ...?

**Comment by MichaelClerx** [comment]
> separating out their parameters from their model by forcing them to use a constant to initialise them

Not sure what you mean!

My idea of a best practice would be doing this:

- parameters are defined by equations: `p = 10`. This means that, "in my model, p is and always will be, 10".
- states (or other variables changed by resets) define an initial value, e.g. `dx/dt = 5, and x(t0) = 10`
- to separate initial values from the main model, have one file define a variable `x` with `dx/dt=5` and another with a variable `x` with `x(t0) = 10`

So we could write something like that up somewhere. And make clear that there is a difference between `x = 10 forever` and `x(t0) = 10`. Imo the latter should only be used if you for `x` to be updated by ODEs or resets.

**Comment by MichaelClerx** [comment]
If you want parameters in a different file, then just write
```
x = x-from-parameters-file
```
don't write
```
x(t0) = x-from-parameters-file
```

**Comment by MichaelClerx** [comment]
The second has a shorter syntax, but is a more complicated statement

**Comment by kerimoyle** [comment]
I'll put something in the informative spec about this.

**Comment by MichaelClerx** [comment]
So the consensus is that we don't strictly _need_ this construct anymore, but we're keeping it for 1.1 compatibility?

With a line in the informative spec saying the new best practice is to do it differently?

**Comment by kerimoyle** [comment]
See new block in PR from last night?  I'm not sure it's correct, so need help with sanity checks there ... ? #88 or the rendered version is [here](https://cellml-specification-dev.readthedocs.io/en/i56_initial_variables/reference/formal_and_informative/specC06_interpretation_of_initial_values.html)
