### ISSUE TITLE
Representation of numbers in the spec

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#57]
Silly thing, but we're currently writing things like

> the exponent term SHALL have value 1.0

and

> the multiplier term SHALL have value 1.0

but we don't need the ".0" bit here, because (1) I think writing the ".0" is just a habit programmers have to avoid floating point issues when using literals in expressions; while (2) the string "1" is a perfectly valid real number string in CellML

**Comment by agarny** [comment]
Fair point.

**Comment by kerimoyle** [comment]
It's true ... but I'd rather leave it with the 1.0 because of the way that the unit items are treated; some are floats (the exponent and the multpilier) but the prefix must be an integer (if it's a number).  I find it clearer to have this reinforced in the text itself by using decimals where they're floats...?

**Comment by kerimoyle** [comment]
Can I close this one or do I ditch the decimals throughout? @MichaelClerx @agarny @nickerso ?

**Comment by agarny** [comment]
I must confess that although I agree with @MichaelClerx's point, I still like to see the ".0" and this for the reason given by @kerimoyle. So, I would be fine with leaving things as-is (as long as we are being consistent throughout -- we might also want to make a note of this in the specs?).

**Comment by MichaelClerx** [comment]
- Whatever we decide it should be consistent
- I don't want to give the impression that writing "1" instead of "1.0" is somehow wrong in CellML
- Happy to be overruled

@nickerso ?

**Comment by kerimoyle** [comment]
> I don't want to give the impression that writing "1" instead of "1.0" is somehow wrong in CellML

With respect to the prefix values, _only_ "1" is correct (and this is the only place in the spec that this is true ...) With respect to the others, either is fine.  I just want to make sure that people can see that distinction easily (in this place).  If users actually read the words they'll get it right though ... 

We could remove all other decimals but keep these ones for clarity, with a note?  Or ditch them all?  Or leave them all?

**Comment by kerimoyle** [comment]
Ping @MichaelClerx @nickerso @agarny @hsorby

**Comment by hsorby** [comment]
I am ambivalent, when I read this I take away that the value of the item in a numerical sense is one whether it is written as `1.0` or `1` is irrelevant as they have the same value.  I don't take away that writing one or the other would be wrong in CellML.

I do take away that it is subtly hinting that this value is a float.

**Comment by MichaelClerx** [comment]
Let's just leave it then
