### ISSUE TITLE
Initial value cycles

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#58]
I think we're missing a rule that says initial_values can't create cycles?

    <var A init="B">
    <var B init="A">

**Comment by MichaelClerx** [comment]
Or is that just "silly maths" again?

**Comment by agarny** [comment]
This is valid CellML, just "silly maths" indeed.

**Comment by MichaelClerx** [comment]
And then there's `<var A init="A">`

(all these examples are in valid PseudML, just in case you're wondering)

**Comment by agarny** [comment]
PseudML?

**Comment by MichaelClerx** [comment]
Oh dear. That one bothers me actually.
You can write
```
<math>
  x = x
</math>
```
because that just says that x equals itself, which is fine.

But the initial value rule says

> Where the initial_value attribute is a variable reference, it SHALL be interpreted as a statement that the variable on which the attribute appears is equal to the referenced variable under the conditions when the initial value holds.

that is something very different from what we do with the maths!

So

1. Stuff in mathml: Equations which hold eternally. Might be rubbish if your model is silly.
2. Stuff in initial_value attributes: Statements about variable equivalence (!!! that needs rewording, at the very least) at the "initial point"

**Comment by MichaelClerx** [comment]
It _might_ be that changing the wording to "value of" in two places fixes this. Not sure.

So then "maths = eternal truths", "initials = truths about the initial condition" ? And both can be nonsense without affecting validity?

**Comment by nickerso** [comment]
> So then "maths = eternal truths", "initials = truths about the initial condition" ? 

Yes. I think so.

> And both can be nonsense without affecting validity?

exactly.

**Comment by kerimoyle** [comment]
@MichaelClerx do you have wording in mind for this one?  I'll add a comment to the informative spec too.

**Comment by MichaelClerx** [comment]
I think it's entirely for the informative spec this one!
I'd just write that nothing in CellML prohibits you from writing "a has initial value b" and "b has initial value a" or similar constructs. That this is valid CellML just like x = 1/0 but just not a useful thing to do

**Comment by kerimoyle** [comment]
Updated in #88 - see https://cellml-specification-dev.readthedocs.io/en/i56_initial_variables/reference/formal_and_informative/specC06_interpretation_of_initial_values.html for rendered version.
