### ISSUE TITLE
C11.7 is redundant?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#59]
> There MUST NOT be a connection element such that the component referenced by the component_1 attribute is in the hidden set of the component referenced by the component_2 attribute, nor vice versa.

But in C1.10 we've already said

> CellML models MUST only contain map_variables elements where the interface of variable A and the interface of variable B are applicable interfaces.

and there are no applicable interfaces for the hidden set.

Not opposed to leaving it in, but maybe we need to clarify? We already have an "for the avoidance of doubt" in C6.5

**Comment by MichaelClerx** [comment]
Also, why do we explain `map_variables`, which relies on encapsulation, as the first point in C, but leave encapsulation till last?

Would it make more sense to start with component level stuff and only then work out way up to variable level stuff like connections?

Something like

models
units
import units
components
import components
encapsulation
variables
connections

**Comment by nickerso** [comment]
> Not opposed to leaving it in, but maybe we need to clarify?

I suspect this is left over from the change when connections moved the components to the connection element and I we now require at least one `map_variables` child so we avoid ever getting into this situation. Can't see anything against removing that clause.

> Would it make more sense to start with component level stuff and only then work out way up to variable level stuff like connections?

I think there are many potential ways to order the elements in the spec and the way @kerimoyle pulls all the sections together it would be trivial to rearrange. But not sure there is a perfect ordering :) I think as long as there are suitable cross-references then readers can work things out.

**Comment by kerimoyle** [comment]
It's easy to rearrange.  I'd rather get rid of stuff which isn't needed as it will only get confusing!  
In my head units should come after variables, but it makes sense to mimic what the other chapters do too, I guess.

**Comment by kerimoyle** [comment]
I've added the well-worn "for the avoidance of doubt" to point C.9.7 (this being the new C11.7)

The order of section C is now:
1. Interpretation of imports
2. Units reference
3. Interpretation of units
4. Component reference
5. Variable reference
6. Interpretation of initial values
7. Effect of units on variables
8. Interpretation of mathematics
9. Interpretation of encapsulation
10. Interpretation of map_variables
11. Interpretation of variable resets

Does that work ... ?
Rendered version is here: https://cellml-specification-dev.readthedocs.io/en/i59_connections_in_sectionc/reference/formal_and_informative/specC09_interpretation_of_encapsulation.html

**Comment by kerimoyle** [comment]
Closed by #93
