### ISSUE TITLE
Imports and encapsulation

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#60]
@nickerso you might remember this:

What happened to the rules about imports and encapsulation?
E.g. do you get the units for free when you import? And any encapsulated components? What happens if I import both A and B and they're encapsulated; would that count as importing B twice?

**Comment by agarny** [comment]
> E.g. do you get the units for free when you import? And any encapsulated components? What happens if I import both A and B and they're encapsulated; would that count as importing B twice?

I believe this is exactly what libCellML does flattening a model. Ping @hsorby, @kerimoyle.

**Comment by nickerso** [comment]
> do you get the units for free when you import? 
Yes, variables in imported components are always defined by the units in their source model. But those units are not "available" in the importing model unless they are specifically imported.

> And any encapsulated components? 
Yes, when you import a component it includes its encapsulated children. (Importing components does not import siblings or parent components.)

> What happens if I import both A and B and they're encapsulated; would that count as importing B twice?
Yes and no :) The B encapsulated by A will not be visible in the importing model and will be a different instance of B than the one that is directly imported. The B that is directly imported will not be encapsulated by A

**Comment by MichaelClerx** [comment]
Where does it say all that in the spec?

**Comment by nickerso** [comment]
yeah, sorry - forgot to add the comment that we need to check whether this is actually defined in the spec :)

**Comment by kerimoyle** [comment]
It's certainly in the tutorials, which are referred to from the informative blocks in the spec ... but:
- these are for libcellml though - it would probably be good to bring a vanilla version into the cellml-spec site
- it deals with encapsulation and imports separately, perhaps useful to combine them somewhere too?

**Comment by MichaelClerx** [comment]
OK so it's definitely not in the spec then, not just me :D 

I think we've got B3, B4, B6, B7, B14 explaining syntax used in imports, and then C3 says

> Each import element present in a CellML infosets (the importing infoset) SHALL define a new and separate instance of the CellML infoset referenced by the href attribute (the imported infoset). See Units reference and Component reference for the specifics of importing units and components.

while C4 and C6 explain how to refer to things.

No text on how imports are to be interpreted at all then!

**Comment by kerimoyle** [comment]
Do you want more added to what's here already?  See the "See more" blocks on this page: https://cellml-specification.readthedocs.io/en/cellml-2-drafting/reference/specB02.html ... if so, let me know and will put something in.

**Comment by MichaelClerx** [comment]
Hmmm! I don't think there should be any mention of libcellml in the spec. We shouldn't even be thinking about libcellml when we're writing it.
But also there's still nothing about encapsulation in there, even if I click those links. Where does it say about importing units? Importing an encapsulated tree of components? Importing siblings of components?

**Comment by MichaelClerx** [comment]
Also, when did these "see more" sections creep in? I thought the idea was to write a spec without the `[ this is because ... ]` blocks we had in the 1.0/1.1 spec?

**Comment by kerimoyle** [comment]
> Hmmm! I don't think there should be any mention of libcellml in the spec. We shouldn't even be thinking about libcellml when we're writing it.

Don't worry, we're not ;). It's intended that there will be a collection of links at the foot of each page which can direct the user to whatever implementation-specific site they need to see.  Since I'm writing it, libcellml is first off the blocks, but I hope (nudge @agarny ) that there will be similar links for OpenCOR and others there too.

> Also, when did these "see more" sections creep in? I thought the idea was to write a spec without the [ this is because ... ] blocks we had in the 1.0/1.1 spec?

As above, they're not part of the real speccy spec - that's still in a document (ish - it's currently broken into the A, B, C sections) which will be able to be exported as a PDF without the extra sections.  Sphinx means that we can import bits and pieces from it for display, because it makes a whole lot more sense to the user to be able to have some human-readable information and links alongside the legalese text.  If the online user doesn't need any extra help, they don't have to open anything ... but if they do, it's there.  For the purists, the normative spec will always be the underlying, un-commented document.

> But also there's still nothing about encapsulation in there, even if I click those links. Where does it say about importing units? Importing an encapsulated tree of components? Importing siblings of components?

See the second "see more" block under 2?

> 2. Every import element MAY contain one or more specific element children, each of which MUST be of one of the following types:
> An import units element; or
> An import component element.
> 
> See more
> 
> The only items which can be imported directly are component and units items. The intention is that these are modular building blocks, able to be passed between models easily through this import functionality.
> When you import a component, all its variables and encapsulated child component items are imported too, along with any its governing math block and any units items it uses.
> When you import a units item, the child unit items which it contain are imported as well.

I'm happy to extend that section if it doesn't go far enough?

**Comment by kerimoyle** [comment]
(ps - also could rename the "See more +" links to something which was a little clearer that it was not a part of the formal spec? "Translate into human"? "See informative section?" "Help!" etc ...?

**Comment by kerimoyle** [comment]
I will make a new branch so we can wrangle it out ...

**Comment by kerimoyle** [comment]
See #86 not 68 ...

**Comment by kerimoyle** [comment]
Closed by #86
