### ISSUE TITLE
Connection cf. map_variables

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#62]
In neither the map_variables nor the connection section do we say that the components have to be siblings or in a parent-child relationship ... should we be?  We specify it later on in the map_variables section, but I think it would be cleaner in the connection section instead?

Currently:
**15 Connection**
1. Each connection element MUST contain a component_1 attribute. The value of the component_1 attribute MUST be a valid CellML identifier.  The value of this attribute MUST be equal to the name attribute on a component or import component element in the CellML infoset (see Component reference).
5. Each connection element MUST contain a component_2 attribute. The value of the component_2 attribute MUST be a valid CellML identifier. The value of this attribute MUST be equal to the name attribute on a component or import component element in the CellML infoset (see Component reference).
9. The value of the connection_1 attribute MUST NOT be equal to the value of the component_2 attribute.
10. A CellML infoset MUST NOT contain more than one connection element with a given pair of components referenced by the component_1 and component_2 attribute values, in any order.
11. Every connection element MUST contain one or more map_variables elements.

**Map_variables**
1. Each map_variables element MUST contain a variable_1 attribute. The value of the variable_1 attribute MUST be a valid CellML identifier.  The value of this attribute MUST be equal to the name attribute on a variable element child of the component element or import component element referenced by the component_1 attribute on the connection element which is the parent of this element.

... etc...

I suggest adding a point to the `connection` section:
x. The components specified by the `component_1` and `component_2` attributes must be visible to one another; that is, either in a parent-child relationship, or siblings in the same encapsulation parent.  See section ?? for details.

**Comment by nickerso** [comment]
I don't think that is necessary. This is purely defining the rules for the connections syntax. Valid connections are defined elsewhere. The parent-child relationship quoted for the `map_variables` is for the syntax not the encapsulation.

**Comment by kerimoyle** [comment]
My mistake.  We don't mention it in the map_variables section either...

**Comment by kerimoyle** [comment]
So why, if this section (B) is only about syntax, do we have other restrictions like "can't be duplicated, can't reference yourself" etc?  I would have thought that this fell into the same category?

**Comment by nickerso** [comment]
We're not big on consistency in the spec :)

But I think those are mostly restrictions on what the values of those things can be, without needing to worry about external things which affect the validity of the values...but if I remember correctly, I suspect in the spec we are simply lumping those external things into some of the other sections...

**Comment by kerimoyle** [comment]
> We're not big on consistency in the spec :)

Ummm :)

In the list above, 1, 2, 5 are syntax, 3 and 4 are value/interpretation/restrictions?  Should the value stuff be moved into section C or we do add other value restrictions to it?
