### ISSUE TITLE
Rewording of C1: Imports

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#63]
> Each `import` element present in a CellML infoset (the importing infoset) SHALL define a new and separate instance of the CellML infoset referenced by the `href` attribute (the imported infoset). See Units reference and Component reference for the specifics of importing `units` and `components`.

I can't make sense of the first sentence.  
- Does the spec know about the idea of model flattening (I thought this was an implementation thing)?  
- "separate" from what?  The other components in the importing infoset, or the imported infoset?
- and it doesn't create a whole new model/infoset?  just the component or units item?

Can we perhaps change it to something like:

"Each `import` element present in a CellML infoset (the importing infoset) SHALL have the effect of creating a new instance of the imported element, where the imported element is:
- found within the CellML infoset referenced by the `href` attribute, and
- having a type equal to the `import` type specified (`import units` or `import component`), and 
- having a name attribute equal to that of the import reference (`units_ref` or `component_ref`).
See Units reference and Component reference for the specifics of importing `units` and `components`."

**Comment by nickerso** [comment]
> Does the spec know about the idea of model flattening (I thought this was an implementation thing)?

correct, the spec knows nothing about flattening.

> "separate" from what? The other components in the importing infoset, or the imported infoset?

separate from any other imported infoset (other `import` elements)

> and it doesn't create a whole new model/infoset? just the component or units item?

yes then no :) The import itself creates a new instance of the imported model (in its entirety) and then the imported components and units are what are in scope of the importing infoset (model). This is needed to ensure units and encapsulated children exist even though that are not directly imported.

Happy to clarify if needed, but don't think the suggested change is correct given the above comments.

**Comment by kerimoyle** [comment]
I don't understand this bit:
> yes then no :) The import itself creates a new instance of the imported model (in its entirety) and then the imported components and units are what are in scope of the importing infoset (model). This is needed to ensure units and encapsulated children exist even though that are not directly imported.

If we're not talking about implementation at all, how does CellML "create a new instance" of anything?  Doesn't it just reference what's there, including down through inherited references to units and other components via the imported item?

**Comment by nickerso** [comment]
Its a conceptual instance, no need for an implementation but need for a scope to be defined so that it is clear what is actually expected to happen. I think this also comes back to #60. And I think that the specification drafted in the original post is not defining the correct scope on things.

**Comment by kerimoyle** [comment]
OK, so how about:
Each `import` element present in a CellML infoset (the importing infoset) SHALL define its scope using the `href` attribute (the imported infoset) and create a new and separate instance of the element referenced.

**Comment by kerimoyle** [comment]
See #86 not #68

**Comment by kerimoyle** [comment]
Closed by #86

**Comment by kerimoyle** [comment]
Closed by #86
