### ISSUE TITLE
_ref vs reference?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#64]
We throw around the terms "units reference" and `units_ref`, and "component reference" and `component_ref` ... but they don't seem to be consistent (or at least, I'm confused ...)  

**Q0:** Can we add a rider to the beginning of C2 and C4 just saying what we're talking about?

"A "component reference" refers to the `component_ref` attributes used in `encapsulation` and `import component` items, and the `component_1` and `component_2` attributes used in `connection` items."

"A "units reference" refers to the `units_ref` attribute in `import units` items, and the `units` attribute used in `unit` and `variable` items."

> C4: Component reference
> A component reference SHALL be the **name of a component**, and SHALL be interpreted based on the **context within the CellML model in which it occurs**.

**Q1:** `component_ref` attributes are used in `encapsulations` and `imports`;`component_1` and `component_2` attributes are used in `connections`... but are all of these covered under the "component reference" title? In which case, I think we need to separate the imports from the others, as otherwise the "context within the CellML model in which it occurs" is a bit weird?

> C2: Units reference
> A units reference SHALL be **a CellML identifier** and SHALL be interpreted dependent on the context of the CellML model in which it occurs, according to the units referencing rules defined later in this section.

**Q2:** Why is this a CellML identifier when the component reference has "a component name".  Should they be the same, and if so, which is better?

> 1. A units reference SHALL be a CellML identifier and SHALL be interpreted dependent on the context of the CellML model in which it occurs, according to the units referencing rules defined later in this section.
> 2. A CellML infoset MUST NOT contain a units reference for which no referencing rule can be held to have been followed.
> 3. The units referencing rules are:
>    1. Where there is a units element **??where??** with a name attribute identical to the units reference, then the units reference SHALL refer to that units element.
>    2. Where there is an import units element in the CellML infoset, such that the import units element has a name attribute identical to the units reference, then the units reference SHALL be treated with respect to referencing rules as if the units reference appeared in the imported infoset, and referring **(referred?)** to the name specified in the units_ref attribute of the import units element.
>    3. Where the units reference is equal to the value in the ‘Name’ column of the Built-in units table, then the units reference SHALL be a reference to the built-in units corresponding to that row of the table.

**Q3:** Can we rearrange the order of these points to make it clearer without referring to "later in this section" stuff? eg: move 1 to be 3.1, 2 to after 3?

**Comment by nickerso** [comment]
Q0 - yes, that is probably a good idea, and even better if can be automated :) But maybe just be careful as encapsulation uses a `component_ref` element, not attribute.

Q1 - not sure I follow, imports are the only one with a `component_ref` attribute, which is interpreted in the context of the model in which it appears, i.e., the `import`.

Q2 - I agree. To me "component name" is the correct thing to use for component references, but I think the difference with units is that they may also point to the built in units, so it might not be always correct to simply say "units name"? But if it is, then I'd suggest that is the way to go.

Q3 - sounds good to me.

**Comment by kerimoyle** [comment]
Ah, you're right, the `component_ref` can be an element too.  But do we use "component reference" to mean all three of them?  Either way, I think it would be good to make the distinction between each case a bit clearer ... the extra typing seems to be outweighed by actually making sense (imho) :)

**Comment by kerimoyle** [comment]
See #86 not #68

**Comment by kerimoyle** [comment]
Closed by #86

**Comment by kerimoyle** [comment]
Closed by #86
