### ISSUE TITLE
Source code formatting

### ISSUE THREAD

**Issue by agarny** [cellml/cellml-specification#72]
The idea is to ensure that our reST code is easily maintainable. This means (to be completed, if needed):
 - [x] Have one sentence per line (this makes it much easier to do a `diff`).

**Comment by kerimoyle** [comment]
Unfortunately, the rst linter complains about lines which are more than 80 characters long.  This is why changing one word somewhere can have a knockon effect on the rest of the paragraph ... :(

**Comment by MichaelClerx** [comment]
Can we not disable that somehow?

**Comment by MichaelClerx** [comment]
Uhm, locally I can build documentation with longer lines just fine. Is there some extra tool involved beyond sphinx?

**Comment by kerimoyle** [comment]
It's not a thing with building, it just gives me warnings locally.  If anyone is volunteering to go through and change everything into one line per sentence (it wasn't like that coming from the google doc!) they are more than welcome ...

**Comment by MichaelClerx** [comment]
Sure!

**Comment by kerimoyle** [comment]
Hey @MichaelClerx  ... so far so good, but do you know why the magical conversion stopped partway through some of the files?  Have a look at `reference/sectionB_elements.rst` for an example?

**Comment by MichaelClerx** [comment]
Hmmm, will have another go!

**Comment by MichaelClerx** [comment]
Not sure what happened there, either I missed a massive chunk or something happened with merging / some new PR overwrote things?

**Comment by kerimoyle** [comment]
Not sure either. I originally thought I'd screwed it up with a PR, but couldn't find where it had happened if so ... (doesn't mean it wasn't me somewhere else though!).  Thanks for fixing :)

**Comment by kerimoyle** [comment]
Closing as now in practice, fixed since #80
