### ISSUE TITLE
Any reason for preferring :code:`x` over ``x`` ?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#73]
We use
```
:code:`x`
```
instead of the shorter
```
``x``
```
does anybody know if these are equivalent?

**Comment by kerimoyle** [comment]
They're kind of equivalent, but I've used :code:`x` because it allows for easier styling, and also for easier original change from the google doc (where I needed to avoid ``).

**Comment by MichaelClerx** [comment]
Thanks!
