### ISSUE TITLE
PDF version of pure formal spec only

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#77]
For the purists, a PDF version of the normative spec only (ie: without the notes from the informative sections) needs to be available.

**Comment by kerimoyle** [comment]
Apparently this isn't possible through readthedocs (though is possible elsewhere) to automagically serve two separate PDF documents, so we'd need to have separate branches (boo) to enable people to be able to download a "manual-type" document of the annotated spec, if we wanted that.  What do others think?  
Option 1:  PDF download is formal spec only, no notes.
Option 2: PDF download of formal spec AND PDF download of annotated/informative spec too? This will mean either a) maintaining two branches only for this purpose, or b) serving a static copy of the formal spec as a PDF, and allowing download of the informative spec as the locally-built PDF?

**Comment by agarny** [comment]
I would probably go with option 1. Easier to maintain. Also, people who want/need the notes will probably be just fine with just an HTML-based version (I probably would be).

**Comment by MichaelClerx** [comment]
Is readthedocs going to be the official way we spread it anyway? Or is that a development thing?
It could end up a bit weird with versioning and such, and possibly lead to lots of slightly different versions of the spec floating around?

**Comment by kerimoyle** [comment]
I'm struggling to get the PDF and HTML versions to match.  The Latex writer insists on numbering the chapters, thus introducing an extra place in the overall numbering of headings.  I've tried various combinations and fixes as recommended in the sphinx/rtd docs, but alas, not getting very far.  Does anyone have any experience/thoughts/advice/whatever ?  Here's what I'm talking about:

HTML version:  Uses "Section A" and then numbers
![image](https://user-images.githubusercontent.com/46887220/77264480-4945e880-6cff-11ea-9818-f16ae2561739.png)

PDF version: Uses "Chapter 1: Section A" and then numbers
![image](https://user-images.githubusercontent.com/46887220/77264556-75616980-6cff-11ea-9f59-0c1ca4f5f710.png)

Thus, A.2.1 has become 1.2.1.  If we're going to stick with this higher-level thing (the sections A, B, etc) then that effectively adds another level of division, so we have (down the tree) 5 levels of points/sub-points if these chapter numbers stay ... which isn't great.  Any ideas?

> Is readthedocs going to be the official way we spread it anyway? Or is that a development thing?
> It could end up a bit weird with versioning and such, and possibly lead to lots of slightly different versions of the spec floating around?

@MichaelClerx As with anything else, I'd expect this to have a draft working version which changes with contributions, and a fixed release version which does not.  The fixed release one will be the "real" spec, I'd imagine?  Not sure how it would be "shared" - once we've generated a PDF we can do what we like with it?

**Comment by nickerso** [comment]
We don't want to get to a situation where the PDF doesn't match the HTML available on ReadTheDocs. I think we are going to end up with two separate repositories. One is the pure normative spec, and will be available at https://www.cellml.org/specifications/cellml_2.0 - a PDF only document could be ok, although I suspect having a browse-able version in HTML would be nice.

The informative version which has all the notes etc. is a separate thing which will live at a different URL, and linked to from the normative spec. Ideally this would be a separate repository which has the normative spec as a git submodule. We need that clear distinction in changing the normative spec vs changing the informative.

**Comment by kerimoyle** [comment]
The formal and informative versions both take the "formal" sections from the same document(s) - I think this is important for keeping them consistent.  The "informative" simply adds blocks throughout the _rendering_ of that document, not to its contents.  
All other aspects are fine, it's just (just!) these chapter headings that I can't turn off ...

**Comment by kerimoyle** [comment]
The easiest "fix" would be to simply rename Section A etc to be Chapter 1 etc.

**Comment by agarny** [comment]
> The easiest "fix" would be to simply rename Section A etc to be Chapter 1 etc.

Looks like the best way forward.

**Comment by nickerso** [comment]
> The formal and informative versions both take the "formal" sections from the same document(s) - I think this is important for keeping them consistent. The "informative" simply adds blocks throughout the _rendering_ of that document, not to its contents.

Yep, exactly. The next step is to separate these documents into different repos so that we can independently track their provenance. Once we are happy with the content and changes stop going in.

But needs a git expert to do the separation so that we don't get things messed up :) 



> > The easiest "fix" would be to simply rename Section A etc to be Chapter 1 etc.
> 
> Looks like the best way forward.

I'm fine with that.

**Comment by kerimoyle** [comment]
I don't quite understand the need for separation if we want them to come from the same source?  That was kind of the point ... so that we didn't ever have duplicate information anywhere?

**Comment by nickerso** [comment]
it is the same source, but having them separate makes it clear when the normative spec changes vs when "other stuff" changes, and allows the other stuff to be updated as needed to improve clarity, etc., going forward. The use of git submodules ensures that we keep a single source without duplication, while being clear about the content of each repository. And have clear provenance for the different information.

**Comment by nickerso** [comment]
Just to be clear, we don't need to worry about this yet - and I also wouldn't worry too much about trying to make a PDF that is just the normative spec as part of this just yet.

**Comment by kerimoyle** [comment]
Closed by #95
