### ISSUE TITLE
`CellML2.0` --> `CellML 2.0`

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#79]
Hi all!

Seems we've got "CellML2.0" as one word in a lot of places.

Is this intentional? Seems odd to me

**Comment by agarny** [comment]
I wouldn't expect it to be intentional, but probably due to the conversion? @kerimoyle?

(@MichaelClerx, I would certainly be happy for you to fix this.)

**Comment by kerimoyle** [comment]
It was intentional, but it doesn't need to be followed ;). We have other formats like this, so I was just following those (MathML2 is the one that springs to mind).

**Comment by MichaelClerx** [comment]
Thanks! I'd begun thinking it was intentional after I noticed it was mostly in the informative (non-converted) files.
I've had a bit of a look around and I think MathML are currently using a space too: https://www.w3.org/TR/MathML2/

e.g. 
> The basic structure of this document is the same as that of the earlier MathML 2.0 Recommendation

**Comment by kerimoyle** [comment]
Closed by #81
