### ISSUE TITLE
Rules from the original specification possibly not included

### ISSUE THREAD

**Issue by agarny** [cellml/cellml-specification#8]
Originally from [jonc125](https://github.com/jonc125):

We may or may not want to include each of these somewhere.
- The definitions of quantitative & qualitative models, conformance levels, and the term "for interoperability"
- 2.4.3 bullet 3 (extension elements cannot contain content in the CellML namespace)
- 2.5.2 (but this rule conflicts with the namespaces in XML recommendation, so should be dropped)
- 3.4.5.4 bullet 2 (each map_components element must declare a unique pair of components to connect)
- 4.2.1 "CellML processing software must interpret MathML elements according to the semantics defined in the MathML 2.0 Recommendation."
- 4.2.3 (the CellML subset of MathML)
- 5.5.2 (Units associated with the MathML constants elements)
- 6.4.3.2 bullet 1 (I think the normative spec makes all relationships hierarchical)
- Section 7 (reactions)

**Comment by MichaelClerx** [comment]
@agarny do we still need this and the other tickets from 2014?

**Comment by agarny** [comment]
Things have changed so much since then that my guess is that we probably don't need them. So, probably "safe" to close them.
