### ISSUE TITLE
Change contact address and attribution

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#89]
Add help@physiomeproject.org to the contacts

**Comment by kerimoyle** [comment]
Closed by #90

**Comment by nickerso** [comment]
Just to reopen this one, is there a reason not to use `editors@cellml.org` as the contact address? @agarny @hsorby @kerimoyle @MichaelClerx  (sorry not to think about this earlier...)

**Comment by agarny** [comment]
Hmm... good point! Doh! Definitely +1 for `editors@cellml.org`.

**Comment by kerimoyle** [comment]
Closed by #98
