### ISSUE TITLE
Authors and author order

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#91]
How shall we do this?

Anyone have any strong preferences?

**Comment by kerimoyle** [comment]
I don't mind :) (speaking as a person of rather low rank!)

**Comment by kerimoyle** [comment]
Also order of contributors and acknowledgements?

**Comment by kerimoyle** [comment]
**Authors:**

|   Michael Clerx
|   Michael T. Cooling
|   Jonathan Cooper
|   Alan Garny
|   Keri Moyle
|   David P. Nickerson
|   Hugh Sorby

**Contributors:**

|   Jesús C. Fernández
|   David Brooks
|   Koray Atalag

The authors also wish to acknowledge the significant contribution of the (discontinued) draft CellML 1.2 specification, much of the text of which was incorporated into this specification - although the semantics have changed considerably.
The CellML 1.2 specification was itself the result of a collaborative effort by a number of researchers during 2008-2011\:

|   Andrew K. Miller (who wrote the text reused here),
|   Jonathan Cooper,
|   Justin Marsh,
|   Alan Garny,
|   Randall Britten,
|   Poul Nielsen
|   and David P. Nickerson

**Comment by agarny** [comment]
> Also order of contributors and acknowledgements?

I would. Simpler that way.

**Comment by nickerso** [comment]
I'll take this one....and send round a PR for review.

**Comment by MichaelClerx** [comment]
@nickerso is there some way to check that we've got absolutely anyone who's ever authored a line on e.g. the google doc, the old repo, wherever else development happened?

**Comment by kerimoyle** [comment]
In the google doc go to File > Version history > See version history.  The only people named there are already on our list, or are anonymous users.  That goes back to Sept 2015, not sure about what happened before then ... :)

**Comment by MichaelClerx** [comment]
It was a dark time. We wore bear skins and sat around the fire (on a good day), discussing the semantics of an empty units definition

**Comment by MichaelClerx** [comment]
(I'm not sure I was involved pre 2015)

**Comment by kerimoyle** [comment]
Closed by #100
